import { Link } from "react-router-dom";
import { TypeAnimation } from "react-type-animation";

const Hero = () => {
  return (
    <div className="text-black">
      <div className="max-w-[800px] mt-[-96px] w-screen h-screen mx-auto text-center flex flex-col items-center justify-center">
        <p className="text-gray font-bold p-2">Connecting different cultures in the Philippines</p>
        <img src="/assets/images/logo-2.svg" alt="logo" width={400} height={325} />
        <div className="flex justify-center items-center">
          <p className="md:text-4xl sm:text-4xl text-xl font-bold py-4">Empowering cultures of</p>
          <TypeAnimation
            sequence={[
              "Abra",
              1000,
              "Agusan del Norte",
              1000,
              "Agusan del Sur",
              1000,
              "Aklan",
              1000,
              "Albay",
              1000,
              "Antique",
              1000,
              "Apayao",
              1000,
              "Aurora",
              1000,
              "Basilan",
              1000,
              "Bataan",
              1000,
              "Batanes",
              1000,
              "Batangas",
              1000,
              "Benguet",
              1000,
              "Biliran",
              1000,
              "Bohol",
              1000,
              "Bukidnon",
              1000,
              "Bulacan",
              1000,
              "Cagayan",
              1000,
              "Camarines Norte",
              1000,
              "Camarines Sur",
              1000,
              "Camiguin",
              1000,
              "Capiz",
              1000,
              "Catanduanes",
              1000,
              "Cavite",
              1000,
              "Cebu",
              1000,
              "Compostela Valley",
              1000,
              "Cotabato",
              1000,
              "Davao de Oro",
              1000,
              "Davao del Norte",
              1000,
              "Davao del Sur",
              1000,
              "Davao Occidental",
              1000,
              "Davao Oriental",
              1000,
              "Dinagat Islands",
              1000,
              "Eastern Samar",
              1000,
              "Guimaras",
              1000,
              "Ifugao",
              1000,
              "Ilocos Norte",
              1000,
              "Ilocos Sur",
              1000,
              "Iloilo",
              1000,
              "Isabela",
              1000,
              "Kalinga",
              1000,
              "La Union",
              1000,
              "Laguna",
              1000,
              "Lanao del Norte",
              1000,
              "Lanao del Sur",
              1000,
              "Leyte",
              1000,
              "Maguindanao",
              1000,
              "Marinduque",
              1000,
              "Masbate",
              1000,
              "Misamis Occidental",
              1000,
              "Misamis Oriental",
              1000,
              "Mountain Province",
              1000,
              "Negros Occidental",
              1000,
              "Negros Oriental",
              1000,
              "Northern Samar",
              1000,
              "Nueva Ecija",
              1000,
              "Nueva Vizcaya",
              1000,
              "Occidental Mindoro",
              1000,
              "Oriental Mindoro",
              1000,
              "Palawan",
              1000,
              "Pampanga",
              1000,
              "Pangasinan",
              1000,
              "Quezon",
              1000,
              "Quirino",
              1000,
              "Rizal",
              1000,
              "Romblon",
              1000,
              "Samar",
              1000,
              "Sarangani",
              1000,
              "Siquijor",
              1000,
              "Sorsogon",
              1000,
              "South Cotabato",
              1000,
              "Southern Leyte",
              1000,
              "Sultan Kudarat",
              1000,
              "Sulu",
              1000,
              "Surigao del Norte",
              1000,
              "Surigao del Sur",
              1000,
              "Tarlac",
              1000,
              "Tawi-Tawi",
              1000,
              "Zambales",
              1000,
              "Zamboanga del Norte",
              1000,
              "Zamboanga del Sur",
              1000,
              "Zamboanga Sibugay",
              1000,
            ]}
            wrapper="span"
            speed={1}
            deletionSpeed={1}
            className="md:text-4xl sm:text-4xl text-xl text-primary-1 font-bold md:pl-4 pl-2"
            repeat={Infinity}
          />
        </div>
        <p className="md:text-2xl text-xl font-bold text-gray-500">
          A Social Media Platform Connecting Different Cultures in the Philippines Utilizing
          Content-Based Filtering Algorithms
        </p>
        <Link
          to="/signup"
          className="leftsidebar-create w-[200px] rounded-md font-medium my-6 mx-auto py-3"
        >
          Get Started
        </Link>
      </div>
    </div>
  );
};

export default Hero;
