export const blacklist = [
  "Arse",
  "Ass",
  "Asshole",
  "Homosexual",
  "Homophobic",
  "Racist",
  "Gay",
  "Lgbt",
  "Jew",
  "Jewish",
  "Anti-semitic",
  "Chink",
  "Muslims",
  "Muslim",
  "Isis",
  "Islamophobe",
  "homophobe ",
  "Bombing",
  "Sexyhot",
  "Bastard",
  "Bitch",
  "Fucker",
  "Cunt",
  "Damn",
  "Fuck",
  "Goddamn",
  "Franchezka",
];

export const provinces = [
  { label: "Metro Manila", value: "metro_manila" },
  { label: "Cavite", value: "cavite" },
  { label: "Laguna", value: "laguna" },
  { label: "Batangas", value: "batangas" },
  { label: "Quezon", value: "quezon" },
  { label: "Rizal", value: "rizal" },
  { label: "Bulacan", value: "bulacan" },
  { label: "Pampanga", value: "pampanga" },
  { label: "Nueva Ecija", value: "nueva_ecija" },
] as const;

export const municipals = [
  { label: "Makati City", value: "makati" },
  { label: "Tagaytay City", value: "tagaytay" },
  { label: "San Pedro", value: "san_pedro" },
  { label: "Lipa City", value: "lipa" },
  { label: "Lucena City", value: "lucena" },
  { label: "Antipolo City", value: "antipolo" },
  { label: "Malolos City", value: "malolos" },
  { label: "Angeles City", value: "angeles" },
  { label: "Cabanatuan City", value: "cabanatuan" },
] as const;
