export const filterInappropriateWords = (text: string): string => {
  const inappropriateWords = [
    "Arse",
    "Ass",
    "Asshole",
    "Homosexual",
    "Homophobic",
    "Racist",
    "Gay",
    "Lgbt",
    "Jew",
    "Jewish",
    "Anti-semitic",
    "Chink",
    "Muslims",
    "Muslim",
    "Isis",
    "Islamophobe",
    "homophobe",
    "Bombing",
    "Sexyhot",
    "Bastard",
    "Bitch",
    "Fucker",
    "Cunt",
    "Damn",
    "Fuck",
    "Goddamn",
    "Shit",
    "Motherfucker",
    "Nigga",
    "Nigger",
    "Prick",
    "Shit",
    "shit ass",
    "Shitass",
    "son of a bitch",
    "Whore",
    "Thot",
    "Slut",
    "Faggot",
    "Dick",
    "Pussy",
    "Penis",
    "Vagina",
    "Negro",
    "Coon",
    "Bitched",
    "Sexist",
    "Freaking",
    "Cock",
    "Sucker",
    "Lick",
    "Licker",
    "Rape",
    "Molest",
    "Anal",
    "Buttrape",
    "Coont",
    "Cancer",
    "Sex",
    "Retard",
    "Fuckface",
    "Dumbass",
    "5h1t",
    "5hit",
    "A_s_s",
    "a2m",
    "a55",
    "adult",
    "amateur",
    "anal",
    "*fakk*",
    "*fuck*",
    "*fuk+er",
    "*fuk+ers",
    "*fukk*",
    "*ni+g+er*",
    "*testical*",
    "*testicle*",
    "anal",
    "anil+ingus*",
    "anus",
    "anuses",
    "anusez",
    "ar+se",
    "ar+sebadger",
    "ar+sehead*",
    "ar+sehol*",
    "ashol*",
    "ass+",
    "ass+hol",
    "ass+hole*",
    "ass+wipe",
    "aswipe",
    "az+hol",
    "az+hole*",
    "b_d_s_m",
    "ball+bag*",
    "ball+sack*",
    "bastard*",
    "bbc",
    "bellend",
    "biatch*",
    "bitch*",
    "blow_job*",
    "boff+in*",
    "bol+ock+*",
    "bon+er",
    "boo+b",
    "boo+bs",
    "boo+bz",
    "btch",
    "bugg+er*",
    "bul+shit*",
    "butt+",
    "butt+hol",
    "butt+hole*",
    "butt+much*",
    "butt+plug*",
    "carpet_muncher*",
    "cawk",
    "cawks",
    "clit+",
    "clit+er*",
    "clit+or*",
    "clit+s",
    "clit+z",
    "cock",
    "cock_sucker*",
    "cock_suckin*",
    "cockface*",
    "cockhead*",
    "cockmunch*",
    "cocknose*",
    "cocks",
    "cocks_sucker*",
    "cockwomble",
    "cockz",
    "crap",
    "cum",
    "cum+er",
    "cum+ing",
    "cumbub+le*",
    "cumdumpst*",
    "cumshot*",
    "cumwipe",
    "cun+il+ingus*",
    "cunt+",
    "cuntlick*",
    "cuntpud+le",
    "damn*",
    "dick",
    "dickhead*",
    "dicks",
    "dickwe+d*",
    "dickweasel",
    "dike",
    "dikes",
    "dil+do*",
    "dog+ie_styl*",
    "dog+y_styl*",
    "douche_bag",
    "douche_bags",
    "dupa",
    "dyke",
    "dykes",
    "ejackulate",
    "erotic*",
    "escort*",
    "fackin*",
    "fag",
    "fagat",
    "faget",
    "fagg+ot*",
    "fagget",
    "faggit",
    "faggt",
    "fagt",
    "fan+yflap*",
    "fatass*",
    "feasting",
    "fecal",
    "fingerfack*",
    "foreskin*",
    "fuk",
    "fuk+ah",
    "fuk+in*",
    "fy",
    "gang+_b+ang*",
    "get_laid",
    "gobshit+*",
    "god+am",
    "god+amn*",
    "godsd+am",
    "godsd+amn*",
    "gook",
    "got_laid",
    "hard_on",
    "hoer",
    "hooker*",
    "hore",
    "horny",
    "horsesh+it+",
    "idiot*",
    "j_o_i",
    "jack_as+",
    "jack_off",
    "jack_sh+it+",
    "jap",
    "japs",
    "jerk_off",
    "jiz+_stain",
    "jiz+breath",
    "jiz+cock",
    "joi",
    "kike",
    "kinky",
    "klit",
    "knob",
    "knobbing",
    "knobhead*",
    "kunt",
    "kunts",
    "kuntz",
    "ladyboy*",
    "lesbo",
    "masturbat*",
    "milf",
    "nazi",
    "nazis*",
    "naziz",
    "negr",
    "neo_nazi+",
    "ni+g+r",
    "ni+g+rs",
    "ni+gg+",
    "nimphoman*",
    "nip+le",
    "nip+les",
    "nutsack*",
    "nutsuck*",
    "orgas+m",
    "orgas+mo",
    "paedofil*",
    "paedophil*",
    "pedofil*",
    "pedophil*",
    "penis*",
    "phuck*",
    "pimp",
    "pimpis",
    "pimps",
    "pimpz",
    "pis+flap*",
    "pis+ing",
    "pis+wizard",
    "piss+",
    "porn",
    "porno",
    "prick+",
    "puss+e",
    "puss+y",
    "quim",
    "rape",
    "raping",
    "rectum",
    "redneck*",
    "s.o.b",
    "sadism*",
    "semen",
    "sex",
    "sexy",
    "sh+-it+",
    "sh+it+",
    "sh+it+e",
    "sh+it+y",
    "sh+it_hol*",
    "shemale*",
    "shit+bag*",
    "shit+house",
    "shit+magnet",
    "shit+pouch",
    "skanck",
    "skank",
    "slut+",
    "slut+y",
    "strap_on",
    "suicid*",
    "svastik*",
    "swastik*",
    "swinger",
    "threesome",
    "thundercunt*",
    "tit+",
    "tit+ie",
    "tit+ies",
    "tit+s",
    "tit+ywank",
    "todger",
    "turd",
    "twat",
    "twat+waf+l*",
    "twathead*",
    "twatty*",
    "twunt",
    "twunter",
    "vagina*",
    "viagra*",
    "vibrator",
    "voyeur*",
    "voyuer*",
    "vul+va*",
    "wank",
    "wanker*",
    "wankface",
    "wetback*",
    "whoar",
    "whore",
    "wiseass+",
    "wtf",
    "xrated",
    "zo+phil+i*",
    //FILIPINO
    "ampota",
    "bobo",
    "bwisit",
    "gago",
    "hayop",
    "hinayupak",
    "leche",
    "putang ina",
    "shunga",
    "tang ina",
    "ulol",
    "amputa",
    "animal ka",
    "bilat",
    "binibrocha",
    "bobo",
    "bogo",
    "boto",
    "brocha",
    "burat",
    "buset",
    "bwesit",
    "bwisit",
    "demonyo ka",
    "engot",
    "etits",
    "gaga",
    "gagi",
    "gago",
    "habal",
    "hayop ka",
    "hayup",
    "hinampak",
    "hinayupak",
    "hindot",
    "hindutan",
    "hudas",
    "iniyot",
    "inutel",
    "inutil",
    "iyot",
    "kagaguhan",
    "kagang",
    "kantot",
    "kantotan",
    "kantut",
    "kantutan",
    "kaululan",
    "kayat",
    "kiki",
    "kikinginamo",
    "kingina",
    "kupal",
    "leche",
    "leching",
    "lechugas",
    "lintik",
    "nakakaburat",
    "nimal",
    "ogag",
    "olok",
    "pakingshet",
    "pakshet",
    "pakyu",
    "pesteng yawa",
    "poke",
    "poki",
    "pokpok",
    "poyet",
    "pu'keng",
    "pucha",
    "puchanggala",
    "puchangina",
    "puke",
    "puki",
    "pukinangina",
    "puking",
    "punyeta",
    "puta",
    "putang",
    "putang ina",
    "putangina",
    "putanginamo",
    "putaragis",
    "putragis",
    "puyet",
    "ratbu",
    "shunga",
    "sira ulo",
    "siraulo",
    "suso",
    "susu",
    "tae",
    "taena",
    "tamod",
    "tanga",
    "tangina",
    "taragis",
    "tarantado",
    "tete",
    "teti",
    "timang",
    "tinil",
    "tite",
    "titi",
    "tungaw",
    "ulol",
    "ulul",
    "ungas",
  ];

  const lookalikeCharacters: Record<string, string> = {
    $: "s",
    "@": "a",
    "<": "c",
    "!": "i",
    "+": "t",
    "0": "o",
    "1": "i",
    "2": "z",
    "3": "z",
    "5": "s",
    "8": "b",
  };

  const escapeRegExp = (str: string) => {
    return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"); // Escape special characters
  };

  const replaceLookalikeCharacters = (word: string): string => {
    let replacedWord = word;

    for (const [lookalike, replacement] of Object.entries(lookalikeCharacters)) {
      const regex = new RegExp(escapeRegExp(lookalike), "gi");
      replacedWord = replacedWord.replace(regex, replacement);
    }

    return replacedWord;
  };

  let filteredText = replaceLookalikeCharacters(text);

  inappropriateWords.forEach((word) => {
    const replacedWord = replaceLookalikeCharacters(word);
    const regex = new RegExp(`\\b${escapeRegExp(replacedWord)}\\b`, "gi");
    filteredText = filteredText.replace(regex, (match) => {
      return match.replace(/[aeiouAEIOU]/g, "*"); // Replace vowels with asterisks
    });
  });

  return filteredText;
};
