export const filterInappropriateWords = (text: string): string => {
  const inappropriateWords = [
    "Arse",
    "Ass",
    "Asshole",
    "Homosexual",
    "Homophobic",
    "Racist",
    "Gay",
    "Lgbt",
    "Jew",
    "Jewish",
    "Anti-semitic",
    "Chink",
    "Muslims",
    "Muslim",
    "Isis",
    "Islamophobe",
    "homophobe",
    "Bombing",
    "Sexyhot",
    "Bastard",
    "Bitch",
    "Fucker",
    "Cunt",
    "Damn",
    "Fuck",
    "Goddamn",
    "Shit",
    "Motherfucker",
    "Nigga",
    "Nigger",
    "Prick",
    "Shit",
    "shit ass",
    "Shitass",
    "son of a bitch",
    "Whore",
    "Thot",
    "Slut",
    "Faggot",
    "Dick",
    "Pussy",
    "Penis",
    "Vagina",
    "Negro",
    "Coon",
    "Bitched",
    "Sexist",
    "Freaking",
    "Cock",
    "Sucker",
    "Lick",
    "Licker",
    "Rape",
    "Molest",
    "Anal",
    "Buttrape",
    "Coont",
    "Cancer",
    "Sex",
    "Retard",
    "Fuckface",
    "Dumbass",
    "5h1t",
    "5hit",
    "A_s_s",
    "a2m",
    "a55",
    "adult",
    "amateur",
    "anal",
  ];

  // Replace inappropriate words with asterisks
  let filteredText = text;
  inappropriateWords.forEach((word) => {
    const regex = new RegExp(`\\b${word}\\b`, "gi"); // Match whole word, case-insensitive
    filteredText = filteredText.replace(regex, "*".repeat(word.length));
  });

  return filteredText;
};
