interface ProvinceOption {
  value: string;
  label: string;
}

export const provinces: ProvinceOption[] = [
  { value: "Abra", label: "Abra" },
  { value: "Agusan del Norte", label: "Agusan del Norte" },
  { value: "Agusan del Sur", label: "Agusan del Sur" },
  { value: "Aklan", label: "Aklan" },
  { value: "Albay", label: "Albay" },
  { value: "Antique", label: "Antique" },
  { value: "Apayao", label: "Apayao" },
  { value: "Aurora", label: "Aurora" },
  { value: "Basilan", label: "Basilan" },
  { value: "Bataan", label: "Bataan" },
  { value: "Batanes", label: "Batanes" },
  { value: "Batangas", label: "Batangas" },
  { value: "Benguet", label: "Benguet" },
  { value: "Biliran", label: "Biliran" },
  { value: "Bohol", label: "Bohol" },
  { value: "Bukidnon", label: "Bukidnon" },
  { value: "Bulacan", label: "Bulacan" },
  { value: "Cagayan", label: "Cagayan" },
  { value: "Camarines Norte", label: "Camarines Norte" },
  { value: "Camarines Sur", label: "Camarines Sur" },
  { value: "Camiguin", label: "Camiguin" },
  { value: "Capiz", label: "Capiz" },
  { value: "Catanduanes", label: "Catanduanes" },
  { value: "Cavite", label: "Cavite" },
  { value: "Cebu", label: "Cebu" },
  { value: "Compostela Valley", label: "Compostela Valley" },
  { value: "Cotabato", label: "Cotabato" },
  { value: "Davao de Oro (Compostela Valley)", label: "Davao de Oro (Compostela Valley)" },
  { value: "Davao del Norte", label: "Davao del Norte" },
  { value: "Davao del Sur", label: "Davao del Sur" },
  { value: "Davao Occidental", label: "Davao Occidental" },
  { value: "Davao Oriental", label: "Davao Oriental" },
  { value: "Dinagat Islands", label: "Dinagat Islands" },
  { value: "Eastern Samar", label: "Eastern Samar" },
  { value: "Guimaras", label: "Guimaras" },
  { value: "Ifugao", label: "Ifugao" },
  { value: "Ilocos Norte", label: "Ilocos Norte" },
  { value: "Ilocos Sur", label: "Ilocos Sur" },
  { value: "Iloilo", label: "Iloilo" },
  { value: "Isabela", label: "Isabela" },
  { value: "Kalinga", label: "Kalinga" },
  { value: "La Union", label: "La Union" },
  { value: "Laguna", label: "Laguna" },
  { value: "Lanao del Norte", label: "Lanao del Norte" },
  { value: "Lanao del Sur", label: "Lanao del Sur" },
  { value: "Leyte", label: "Leyte" },
  { value: "Maguindanao", label: "Maguindanao" },
  { value: "Marinduque", label: "Marinduque" },
  { value: "Masbate", label: "Masbate" },
  { value: "Metro Manila", label: "Metro Manila" },
  { value: "Misamis Occidental", label: "Misamis Occidental" },
  { value: "Misamis Oriental", label: "Misamis Oriental" },
  { value: "Mountain Province", label: "Mountain Province" },
  { value: "Negros Occidental", label: "Negros Occidental" },
  { value: "Negros Oriental", label: "Negros Oriental" },
  { value: "Northern Samar", label: "Northern Samar" },
  { value: "Nueva Ecija", label: "Nueva Ecija" },
  { value: "Nueva Vizcaya", label: "Nueva Vizcaya" },
  { value: "Occidental Mindoro", label: "Occidental Mindoro" },
  { value: "Oriental Mindoro", label: "Oriental Mindoro" },
  { value: "Palawan", label: "Palawan" },
  { value: "Pampanga", label: "Pampanga" },
  { value: "Pangasinan", label: "Pangasinan" },
  { value: "Quezon", label: "Quezon" },
  { value: "Quirino", label: "Quirino" },
  { value: "Rizal", label: "Rizal" },
  { value: "Romblon", label: "Romblon" },
  { value: "Samar", label: "Samar" },
  { value: "Sarangani", label: "Sarangani" },
  { value: "Siquijor", label: "Siquijor" },
  { value: "Sorsogon", label: "Sorsogon" },
  { value: "South Cotabato", label: "South Cotabato" },
  { value: "Southern Leyte", label: "Southern Leyte" },
  { value: "Sultan Kudarat", label: "Sultan Kudarat" },
  { value: "Sulu", label: "Sulu" },
  { value: "Surigao del Norte", label: "Surigao del Norte" },
  { value: "Surigao del Sur", label: "Surigao del Sur" },
  { value: "Tarlac", label: "Tarlac" },
  { value: "Tawi-Tawi", label: "Tawi-Tawi" },
  { value: "Zambales", label: "Zambales" },
  { value: "Zamboanga del Norte", label: "Zamboanga del Norte" },
  { value: "Zamboanga del Sur", label: "Zamboanga del Sur" },
  { value: "Zamboanga Sibugay", label: "Zamboanga Sibugay" },
];

export const provincesTest = [
  { value: "abra", label: "Abra" },
  { value: "agusan_del_norte", label: "Agusan del Norte" },
  { value: "agusan_del_sur", label: "Agusan del Sur" },
  { value: "aklan", label: "Aklan" },
  { value: "albay", label: "Albay" },
  { value: "antique", label: "Antique" },
  { value: "apayao", label: "Apayao" },
  { value: "aurora", label: "Aurora" },
  { value: "basilan", label: "Basilan" },
  { value: "bataan", label: "Bataan" },
  { value: "batanes", label: "Batanes" },
  { value: "batangas", label: "Batangas" },
  { value: "benguet", label: "Benguet" },
  { value: "biliran", label: "Biliran" },
  { value: "bohol", label: "Bohol" },
  { value: "bukidnon", label: "Bukidnon" },
  { value: "bulacan", label: "Bulacan" },
  { value: "cagayan", label: "Cagayan" },
  { value: "camarines_norte", label: "Camarines Norte" },
  { value: "camarines_sur", label: "Camarines Sur" },
  { value: "camiguin", label: "Camiguin" },
  { value: "capiz", label: "Capiz" },
  { value: "catanduanes", label: "Catanduanes" },
  { value: "cavite", label: "Cavite" },
  { value: "cebu", label: "Cebu" },
  { value: "compostela_valley", label: "Compostela Valley" },
  { value: "cotabato", label: "Cotabato" },
  { value: "davao_de_oro", label: "Davao de Oro (Compostela Valley)" },
  { value: "davao_del_norte", label: "Davao del Norte" },
  { value: "davao_del_sur", label: "Davao del Sur" },
  { value: "davao_occidental", label: "Davao Occidental" },
  { value: "davao_oriental", label: "Davao Oriental" },
  { value: "dinagat_islands", label: "Dinagat Islands" },
  { value: "eastern_samar", label: "Eastern Samar" },
  { value: "guimaras", label: "Guimaras" },
  { value: "ifugao", label: "Ifugao" },
  { value: "ilocos_norte", label: "Ilocos Norte" },
  { value: "ilocos_sur", label: "Ilocos Sur" },
  { value: "iloilo", label: "Iloilo" },
  { value: "isabela", label: "Isabela" },
  { value: "kalinga", label: "Kalinga" },
  { value: "la_union", label: "La Union" },
  { value: "laguna", label: "Laguna" },
  { value: "lanao_del_norte", label: "Lanao del Norte" },
  { value: "lanao_del_sur", label: "Lanao del Sur" },
  { value: "leyte", label: "Leyte" },
  { value: "maguindanao", label: "Maguindanao" },
  { value: "marinduque", label: "Marinduque" },
  { value: "masbate", label: "Masbate" },
  { value: "metro_manila", label: "Metro Manila" },
  { value: "misamis_occidental", label: "Misamis Occidental" },
  { value: "misamis_oriental", label: "Misamis Oriental" },
  { value: "mountain_province", label: "Mountain Province" },
  { value: "negros_occidental", label: "Negros Occidental" },
  { value: "negros_oriental", label: "Negros Oriental" },
  { value: "northern_samar", label: "Northern Samar" },
  { value: "nueva_ecija", label: "Nueva Ecija" },
  { value: "nueva_vizcaya", label: "Nueva Vizcaya" },
  { value: "occidental_mindoro", label: "Occidental Mindoro" },
  { value: "oriental_mindoro", label: "Oriental Mindoro" },
  { value: "palawan", label: "Palawan" },
  { value: "pampanga", label: "Pampanga" },
  { value: "pangasinan", label: "Pangasinan" },
  { value: "quezon", label: "Quezon" },
  { value: "quirino", label: "Quirino" },
  { value: "rizal", label: "Rizal" },
  { value: "romblon", label: "Romblon" },
  { value: "samar", label: "Samar" },
  { value: "sarangani", label: "Sarangani" },
  { value: "siquijor", label: "Siquijor" },
  { value: "sorsogon", label: "Sorsogon" },
  { value: "south_cotabato", label: "South Cotabato" },
  { value: "southern_leyte", label: "Southern Leyte" },
  { value: "sultan_kudarat", label: "Sultan Kudarat" },
  { value: "sulu", label: "Sulu" },
  { value: "surigao_del_norte", label: "Surigao del Norte" },
  { value: "surigao_del_sur", label: "Surigao del Sur" },
  { value: "tarlac", label: "Tarlac" },
  { value: "tawi_tawi", label: "Tawi-Tawi" },
  { value: "zambales", label: "Zambales" },
  { value: "zamboanga_del_norte", label: "Zamboanga del Norte" },
  { value: "zamboanga_del_sur", label: "Zamboanga del Sur" },
  { value: "zamboanga_sibugay", label: "Zamboanga Sibugay" },
];

export const municipalities: { [key: string]: { value: string; label: string }[] } = {
  abra: [
    { value: "bangued", label: "Bangued" },
    { value: "boliney", label: "Boliney" },
    { value: "bucay", label: "Bucay" },
    { value: "bucloc", label: "Bucloc" },
    { value: "daguioman", label: "Daguioman" },
    { value: "danglas", label: "Danglas" },
    { value: "dolores", label: "Dolores" },
    { value: "la_paz", label: "La Paz" },
    { value: "lacub", label: "Lacub" },
    { value: "lagangilang", label: "Lagangilang" },
    { value: "lagayan", label: "Lagayan" },
    { value: "langiden", label: "Langiden" },
    { value: "licuan_baay", label: "Licuan-Baay" },
    { value: "luba", label: "Luba" },
    { value: "malibcong", label: "Malibcong" },
    { value: "manabo", label: "Manabo" },
    { value: "penarrubia", label: "Peñarrubia" },
    { value: "pidigan", label: "Pidigan" },
    { value: "pilar", label: "Pilar" },
    { value: "sallapadan", label: "Sallapadan" },
    { value: "san_isidro", label: "San Isidro" },
    { value: "san_juan", label: "San Juan" },
    { value: "san_quintin", label: "San Quintin" },
    { value: "tayum", label: "Tayum" },
    { value: "tineg", label: "Tineg" },
    { value: "tubo", label: "Tubo" },
    { value: "villaviciosa", label: "Villaviciosa" },
  ],
  agusan_del_norte: [
    { value: "cabadbaran", label: "Cabadbaran" },
    { value: "carmen", label: "Carmen" },
    { value: "jabonga", label: "Jabonga" },
    { value: "kitcharao", label: "Kitcharao" },
    { value: "las_nieves", label: "Las Nieves" },
    { value: "magallanes", label: "Magallanes" },
    { value: "nasipit", label: "Nasipit" },
    { value: "remedios_t_romualdez", label: "Remedios T. Romualdez" },
    { value: "santiago", label: "Santiago" },
  ],
  agusan_del_sur: [
    { value: "tubay", label: "Tubay" },
    { value: "bayugan", label: "Bayugan" },
    { value: "bunawan", label: "Bunawan" },
    { value: "esperanza", label: "Esperanza" },
    { value: "la_paz_agusan_del_sur", label: "La Paz" },
    { value: "loreto", label: "Loreto" },
    { value: "prosperidad", label: "Prosperidad" },
    { value: "rosario", label: "Rosario" },
    { value: "san_francisco", label: "San Francisco" },
    { value: "san_luis", label: "San Luis" },
    { value: "santa_josefa", label: "Santa Josefa" },
    { value: "sibagat", label: "Sibagat" },
    { value: "talacogon", label: "Talacogon" },
    { value: "trento", label: "Trento" },
    { value: "veruela", label: "Veruela" },
  ],
  aklan: [
    { value: "altavas", label: "Altavas" },
    { value: "balete", label: "Balete" },
    { value: "banga", label: "Banga" },
    { value: "batan", label: "Batan" },
    { value: "buruanga", label: "Buruanga" },
    { value: "ibajay", label: "Ibajay" },
    { value: "kalibo", label: "Kalibo" },
    { value: "lezo", label: "Lezo" },
    { value: "libacao", label: "Libacao" },
    { value: "madalag", label: "Madalag" },
    { value: "makato", label: "Makato" },
    { value: "malay", label: "Malay" },
    { value: "malinao", label: "Malinao" },
    { value: "nabas", label: "Nabas" },
    { value: "new_washington", label: "New Washington" },
    { value: "numancia", label: "Numancia" },
    { value: "tangalan", label: "Tangalan" },
  ],
  albay: [
    { value: "bacacay", label: "Bacacay" },
    { value: "camalig", label: "Camalig" },
    { value: "daraga", label: "Daraga" },
    { value: "guinobatan", label: "Guinobatan" },
    { value: "jovellar", label: "Jovellar" },
    { value: "legazpi", label: "Legazpi" },
    { value: "libon", label: "Libon" },
    { value: "ligao", label: "Ligao" },
    { value: "malilipot", label: "Malilipot" },
    { value: "malinao_albay", label: "Malinao" },
    { value: "manito", label: "Manito" },
    { value: "oas", label: "Oas" },
    { value: "pio_duran", label: "Pio Duran" },
    { value: "polangui", label: "Polangui" },
    { value: "rapu_rapu", label: "Rapu-Rapu" },
    { value: "santo_domingo", label: "Santo Domingo" },
    { value: "tabaco", label: "Tabaco" },
    { value: "tiwi", label: "Tiwi" },
  ],
  antique: [
    { value: "anini_y", label: "Anini-y" },
    { value: "barbaza", label: "Barbaza" },
    { value: "belison", label: "Belison" },
    { value: "bugasong", label: "Bugasong" },
    { value: "caluya", label: "Caluya" },
    { value: "culasi", label: "Culasi" },
    { value: "hamtic", label: "Hamtic" },
    { value: "laua_an", label: "Laua-an" },
    { value: "libertad", label: "Libertad" },
    { value: "pandan", label: "Pandan" },
    { value: "patnongon", label: "Patnongon" },
    { value: "san_jose_de_buenavista", label: "San Jose de Buenavista" },
    { value: "san_remigio", label: "San Remigio" },
    { value: "sebaste", label: "Sebaste" },
    { value: "sibalom", label: "Sibalom" },
    { value: "tibiao", label: "Tibiao" },
    { value: "tobias_fornier", label: "Tobias Fornier" },
    { value: "valderrama", label: "Valderrama" },
  ],
  apayao: [
    { value: "calanasan", label: "Calanasan" },
    { value: "conner", label: "Conner" },
    { value: "flora", label: "Flora" },
    { value: "kabugao", label: "Kabugao" },
    { value: "luna", label: "Luna" },
    { value: "pudtol", label: "Pudtol" },
    { value: "santa_marcela", label: "Santa Marcela" },
  ],
  aurora: [
    { value: "baler", label: "Baler" },
    { value: "casiguran", label: "Casiguran" },
    { value: "dilasag", label: "Dilasag" },
    { value: "dinalungan", label: "Dinalungan" },
    { value: "dingalan", label: "Dingalan" },
    { value: "dipaculao", label: "Dipaculao" },
    { value: "maria_aurora", label: "Maria Aurora" },
    { value: "san_luis", label: "San Luis" },
  ],
  basilan: [
    { value: "akbar", label: "Akbar" },
    { value: "al_barka", label: "Al-Barka" },
    { value: "hadji_mohammad_ajul", label: "Hadji Mohammad Ajul" },
    { value: "hadji_muhtamad", label: "Hadji Muhtamad" },
    { value: "isabela", label: "Isabela" },
    { value: "lamitan", label: "Lamitan" },
    { value: "lantawan", label: "Lantawan" },
    { value: "maluso", label: "Maluso" },
    { value: "sumisip", label: "Sumisip" },
    { value: "tabuan_lasa", label: "Tabuan-Lasa" },
    { value: "tipo_tipo", label: "Tipo-Tipo" },
    { value: "tuburan", label: "Tuburan" },
    { value: "ungkaya_pukan", label: "Ungkaya Pukan" },
  ],
  bataan: [
    { value: "abucay", label: "Abucay" },
    { value: "bagac", label: "Bagac" },
    { value: "balanga", label: "Balanga" },
    { value: "dinalupihan", label: "Dinalupihan" },
    { value: "hermosa", label: "Hermosa" },
    { value: "limay", label: "Limay" },
    { value: "mariveles", label: "Mariveles" },
    { value: "morong", label: "Morong" },
    { value: "orani", label: "Orani" },
    { value: "orion", label: "Orion" },
    { value: "pilar", label: "Pilar" },
    { value: "samal", label: "Samal" },
  ],
  batanes: [
    { value: "basco", label: "Basco" },
    { value: "itbayat", label: "Itbayat" },
    { value: "ivana", label: "Ivana" },
    { value: "mahatao", label: "Mahatao" },
    { value: "sabtang", label: "Sabtang" },
    { value: "uyugan", label: "Uyugan" },
  ],
  batangas: [
    { value: "agoncillo", label: "Agoncillo" },
    { value: "alitagtag", label: "Alitagtag" },
    { value: "balayan", label: "Balayan" },
    { value: "balete_batangas", label: "Balete" },
    { value: "batangas_city", label: "Batangas City" },
    { value: "bauan", label: "Bauan" },
    { value: "calaca", label: "Calaca" },
    { value: "calatagan", label: "Calatagan" },
    { value: "cuenca", label: "Cuenca" },
    { value: "ibaan", label: "Ibaan" },
    { value: "laurel", label: "Laurel" },
    { value: "lemery", label: "Lemery" },
    { value: "lian", label: "Lian" },
    { value: "lipa", label: "Lipa" },
    { value: "lobo", label: "Lobo" },
    { value: "mabini_batangas", label: "Mabini" },
    { value: "malvar", label: "Malvar" },
    { value: "mataasnakahoy", label: "Mataasnakahoy" },
    { value: "nasugbu", label: "Nasugbu" },
    { value: "padre_garcia", label: "Padre Garcia" },
    { value: "rosario_batangas", label: "Rosario" },
    { value: "san_jose_batangas", label: "San Jose" },
    { value: "san_juan_batangas", label: "San Juan" },
    { value: "san_luis_batangas", label: "San Luis" },
    { value: "san_nicolas_batangas", label: "San Nicolas" },
    { value: "san_pascual_batangas", label: "San Pascual" },
    { value: "santa_teresita_batangas", label: "Santa Teresita" },
    { value: "santo_tomas_batangas", label: "Santo Tomas" },
    { value: "taal", label: "Taal" },
    { value: "talisay_batangas", label: "Talisay" },
    { value: "tanauan", label: "Tanauan" },
    { value: "taysan", label: "Taysan" },
    { value: "tingloy", label: "Tingloy" },
    { value: "tuy", label: "Tuy" },
  ],
  benguet: [
    { value: "atok", label: "Atok" },
    { value: "baguio", label: "Baguio" },
    { value: "bakun", label: "Bakun" },
    { value: "bokod", label: "Bokod" },
    { value: "buguias", label: "Buguias" },
    { value: "itogon", label: "Itogon" },
    { value: "kabayan", label: "Kabayan" },
    { value: "kapangan", label: "Kapangan" },
    { value: "kibungan", label: "Kibungan" },
    { value: "la_trinidad", label: "La Trinidad" },
    { value: "mankayan", label: "Mankayan" },
    { value: "sablan", label: "Sablan" },
    { value: "tuba", label: "Tuba" },
    { value: "tublay", label: "Tublay" },
  ],
  biliran: [
    { value: "almeria", label: "Almeria" },
    { value: "biliran", label: "Biliran" },
    { value: "cabucgayan", label: "Cabucgayan" },
    { value: "caibiran", label: "Caibiran" },
    { value: "culaba", label: "Culaba" },
    { value: "kawayan", label: "Kawayan" },
    { value: "maripipi", label: "Maripipi" },
    { value: "naval", label: "Naval" },
  ],
  bohol: [
    { value: "alburquerque", label: "Alburquerque" },
    { value: "alicia", label: "Alicia" },
    { value: "anda", label: "Anda" },
    { value: "antequera", label: "Antequera" },
    { value: "baclayon", label: "Baclayon" },
    { value: "balilihan", label: "Balilihan" },
    { value: "batuan", label: "Batuan" },
    { value: "bien_unido", label: "Bien Unido" },
    { value: "bilar", label: "Bilar" },
    { value: "buenavista_bohol", label: "Buenavista" },
    { value: "calape", label: "Calape" },
    { value: "candijay", label: "Candijay" },
    { value: "carmen_bohol", label: "Carmen" },
    { value: "catigbian", label: "Catigbian" },
    { value: "clarin_bohol", label: "Clarin" },
    { value: "corella", label: "Corella" },
    { value: "cortes_bohol", label: "Cortes" },
    { value: "dagohoy", label: "Dagohoy" },
    { value: "danao_bohol", label: "Danao" },
    { value: "dauis", label: "Dauis" },
    { value: "dimiao", label: "Dimiao" },
    { value: "duero", label: "Duero" },
    { value: "garcia_hernandez", label: "Garcia Hernandez" },
    { value: "getafe", label: "Getafe" },
    { value: "guindulman", label: "Guindulman" },
    { value: "inabanga", label: "Inabanga" },
    { value: "jagna", label: "Jagna" },
    { value: "lila", label: "Lila" },
    { value: "loay", label: "Loay" },
    { value: "loboc", label: "Loboc" },
    { value: "loon", label: "Loon" },
    { value: "mabini_bohol", label: "Mabini" },
    { value: "maribojoc", label: "Maribojoc" },
    { value: "panglao", label: "Panglao" },
    { value: "pilar_bohol", label: "Pilar" },
    { value: "president_carlos_p_garcia", label: "President Carlos P. Garcia" },
    { value: "sagbayan", label: "Sagbayan" },
    { value: "san_isidro_bohol", label: "San Isidro" },
    { value: "san_miguel_bohol", label: "San Miguel" },
    { value: "sevilla", label: "Sevilla" },
    { value: "sierra_bullones", label: "Sierra Bullones" },
    { value: "sikatuna", label: "Sikatuna" },
    { value: "tagbilaran", label: "Tagbilaran" },
    { value: "talibon", label: "Talibon" },
    { value: "trinidad_bohol", label: "Trinidad" },
    { value: "tubigon", label: "Tubigon" },
    { value: "ubay", label: "Ubay" },
    { value: "valencia_bohol", label: "Valencia" },
  ],
  bukidnon: [
    { value: "baungon", label: "Baungon" },
    { value: "cabanglasan", label: "Cabanglasan" },
    { value: "damulog", label: "Damulog" },
    { value: "dangcagan", label: "Dangcagan" },
    { value: "don_carlos", label: "Don Carlos" },
    { value: "impasugong", label: "Impasugong" },
    { value: "kadingilan", label: "Kadingilan" },
    { value: "kalilangan", label: "Kalilangan" },
    { value: "kibawe", label: "Kibawe" },
    { value: "kitaotao", label: "Kitaotao" },
    { value: "lantapan", label: "Lantapan" },
    { value: "libona", label: "Libona" },
    { value: "malaybalay", label: "Malaybalay" },
    { value: "malitbog", label: "Malitbog" },
    { value: "manolo_fortich", label: "Manolo Fortich" },
    { value: "maramag", label: "Maramag" },
    { value: "pangantucan", label: "Pangantucan" },
    { value: "quezon_bukidnon", label: "Quezon" },
    { value: "san_fernando_bukidnon", label: "San Fernando" },
    { value: "sumilao", label: "Sumilao" },
    { value: "talakag", label: "Talakag" },
    { value: "valencia_bukidnon", label: "Valencia" },
  ],
  bulacan: [
    { value: "angat", label: "Angat" },
    { value: "balagtas", label: "Balagtas" },
    { value: "baliwag", label: "Baliwag" },
    { value: "bocaue", label: "Bocaue" },
    { value: "bulakan", label: "Bulakan" },
    { value: "bustos", label: "Bustos" },
    { value: "calumpit", label: "Calumpit" },
    { value: "dona_remedios_trinidad", label: "Doña Remedios Trinidad" },
    { value: "guiguinto", label: "Guiguinto" },
    { value: "hagonoy", label: "Hagonoy" },
    { value: "malolos", label: "Malolos" },
    { value: "marilao", label: "Marilao" },
    { value: "meycauayan", label: "Meycauayan" },
    { value: "norzagaray", label: "Norzagaray" },
    { value: "obando", label: "Obando" },
    { value: "pandi", label: "Pandi" },
    { value: "paombong", label: "Paombong" },
    { value: "plaridel_bulacan", label: "Plaridel" },
    { value: "pulilan", label: "Pulilan" },
    { value: "san_ildefonso", label: "San Ildefonso" },
    { value: "san_jose_del_monte", label: "San Jose del Monte" },
    { value: "san_miguel_bulacan", label: "San Miguel" },
    { value: "san_rafael", label: "San Rafael" },
    { value: "santa_maria_bulacan", label: "Santa Maria" },
  ],
  cagayan: [
    { value: "abulug", label: "Abulug" },
    { value: "alcala", label: "Alcala" },
    { value: "allacapan", label: "Allacapan" },
    { value: "amulung", label: "Amulung" },
    { value: "aparri", label: "Aparri" },
    { value: "baggao", label: "Baggao" },
    { value: "ballesteros", label: "Ballesteros" },
    { value: "buguey", label: "Buguey" },
    { value: "calayan", label: "Calayan" },
    { value: "camalaniugan", label: "Camalaniugan" },
    { value: "claveria", label: "Claveria" },
    { value: "enrile", label: "Enrile" },
    { value: "gattaran", label: "Gattaran" },
    { value: "gonzaga", label: "Gonzaga" },
    { value: "iguig", label: "Iguig" },
    { value: "lal-lo", label: "Lal-lo" },
    { value: "lasam", label: "Lasam" },
    { value: "pamplona", label: "Pamplona" },
    { value: "penablanca", label: "Peñablanca" },
    { value: "piat", label: "Piat" },
    { value: "rizal", label: "Rizal" },
    { value: "sanchez-mira", label: "Sanchez-Mira" },
    { value: "santa_ana", label: "Santa Ana" },
    { value: "santa_praxedes", label: "Santa Praxedes" },
    { value: "santa_teresita", label: "Santa Teresita" },
    { value: "santo_nino", label: "Santo Niño" },
    { value: "solana", label: "Solana" },
    { value: "tuao", label: "Tuao" },
    { value: "tuguegarao", label: "Tuguegarao" },
  ],
  camarines_norte: [
    { value: "basud", label: "Basud" },
    { value: "capalonga", label: "Capalonga" },
    { value: "daet", label: "Daet" },
    { value: "jose_panganiban", label: "Jose Panganiban" },
    { value: "labo", label: "Labo" },
    { value: "mercedes", label: "Mercedes" },
    { value: "paracale", label: "Paracale" },
    { value: "san_lorenzo_ruiz", label: "San Lorenzo Ruiz" },
    { value: "san_vicente", label: "San Vicente" },
    { value: "santa_elena", label: "Santa Elena" },
    { value: "talisay", label: "Talisay" },
    { value: "vinzons", label: "Vinzons" },
  ],
  camarines_sur: [
    { value: "baao", label: "Baao" },
    { value: "balatan", label: "Balatan" },
    { value: "bato", label: "Bato" },
    { value: "bombon", label: "Bombon" },
    { value: "buhi", label: "Buhi" },
    { value: "bula", label: "Bula" },
    { value: "cabusao", label: "Cabusao" },
    { value: "calabanga", label: "Calabanga" },
    { value: "camaligan", label: "Camaligan" },
    { value: "canaman", label: "Canaman" },
    { value: "caramoan", label: "Caramoan" },
    { value: "del_gallego", label: "Del Gallego" },
    { value: "gainza", label: "Gainza" },
    { value: "garchitorena", label: "Garchitorena" },
    { value: "goa", label: "Goa" },
    { value: "iriga", label: "Iriga" },
    { value: "lagonoy", label: "Lagonoy" },
    { value: "libmanan", label: "Libmanan" },
    { value: "lupi", label: "Lupi" },
    { value: "magarao", label: "Magarao" },
    { value: "milaor", label: "Milaor" },
    { value: "minalabac", label: "Minalabac" },
    { value: "nabua", label: "Nabua" },
    { value: "naga", label: "Naga" },
    { value: "ocampo", label: "Ocampo" },
    { value: "pamplona_camsur", label: "Pamplona" },
    { value: "pasacao", label: "Pasacao" },
    { value: "pili", label: "Pili" },
    { value: "presentacion", label: "Presentacion" },
    { value: "ragay", label: "Ragay" },
    { value: "sagnay", label: "Sagñay" },
    { value: "san_fernando_camsur", label: "San Fernando" },
    { value: "san_jose_camsur", label: "San Jose" },
    { value: "sipocot", label: "Sipocot" },
    { value: "siruma", label: "Siruma" },
    { value: "tigaon", label: "Tigaon" },
    { value: "tinambac", label: "Tinambac" },
  ],
  camiguin: [
    { value: "catarman", label: "Catarman" },
    { value: "guinsiliban", label: "Guinsiliban" },
    { value: "mahinog", label: "Mahinog" },
    { value: "mambajao", label: "Mambajao" },
    { value: "sagay_camiguin", label: "Sagay" },
  ],
  capiz: [
    { value: "cuartero", label: "Cuartero" },
    { value: "dao", label: "Dao" },
    { value: "dumalag", label: "Dumalag" },
    { value: "dumarao", label: "Dumarao" },
    { value: "ivisan", label: "Ivisan" },
    { value: "jamindan", label: "Jamindan" },
    { value: "maayon", label: "Ma-ayon" },
    { value: "mambusao", label: "Mambusao" },
    { value: "panay", label: "Panay" },
    { value: "panitan", label: "Panitan" },
    { value: "pilar_capiz", label: "Pilar" },
    { value: "pontevedra", label: "Pontevedra" },
    { value: "president_roxas_capiz", label: "President Roxas" },
    { value: "sapian", label: "Sapian" },
    { value: "sigma", label: "Sigma" },
    { value: "tapaz", label: "Tapaz" },
  ],
  catanduanes: [
    { value: "bagamanoc", label: "Bagamanoc" },
    { value: "baras", label: "Baras" },
    { value: "bato_catanduanes", label: "Bato" },
    { value: "caramoran", label: "Caramoran" },
    { value: "gigmoto", label: "Gigmoto" },
    { value: "pandan_catanduanes", label: "Pandan" },
    { value: "panganiban", label: "Panganiban" },
    { value: "san_andres_catanduanes", label: "San Andres" },
    { value: "san_miguel_catanduanes", label: "San Miguel" },
    { value: "viga", label: "Viga" },
    { value: "virac", label: "Virac" },
  ],
  cavite: [
    { value: "alfonso", label: "Alfonso" },
    { value: "amadeo", label: "Amadeo" },
    { value: "bacoor", label: "Bacoor" },
    { value: "carmona", label: "Carmona" },
    { value: "cavite_city", label: "Cavite City" },
    { value: "dasmarinas", label: "Dasmariñas" },
    { value: "general_emilio_aguinaldo", label: "General Emilio Aguinaldo" },
    { value: "general_mariano_alvarez", label: "General Mariano Alvarez" },
    { value: "general_trias", label: "General Trias" },
    { value: "imus", label: "Imus" },
    { value: "indang", label: "Indang" },
    { value: "kawit", label: "Kawit" },
    { value: "magallanes", label: "Magallanes" },
    { value: "maragondon", label: "Maragondon" },
    { value: "mendez", label: "Mendez" },
    { value: "naic", label: "Naic" },
    { value: "noveleta", label: "Noveleta" },
    { value: "rosario_cavite", label: "Rosario" },
    { value: "silang", label: "Silang" },
    { value: "tagaytay", label: "Tagaytay" },
    { value: "tanza", label: "Tanza" },
    { value: "ternate", label: "Ternate" },
    { value: "trece_martires", label: "Trece Martires" },
  ],
  davao_de_oro: [
    { value: "compostela_davao_de_oro", label: "Compostela" },
    { value: "laak", label: "Laak" },
    { value: "mabini_davao_de_oro", label: "Mabini" },
    { value: "maco", label: "Maco" },
    { value: "maragusan", label: "Maragusan" },
    { value: "mawab", label: "Mawab" },
    { value: "monkayo", label: "Monkayo" },
    { value: "montevista", label: "Montevista" },
    { value: "nabunturan", label: "Nabunturan" },
    { value: "new_bataan", label: "New Bataan" },
    { value: "pantukan", label: "Pantukan" },
  ],
  davao_del_norte: [
    { value: "asuncion", label: "Asuncion" },
    { value: "braulio_e_dujali", label: "Braulio E. Dujali" },
    { value: "carmen_davao_del_norte", label: "Carmen" },
    { value: "kapalong", label: "Kapalong" },
    { value: "new_corella", label: "New Corella" },
    { value: "panabo", label: "Panabo" },
    { value: "samal_davao_del_norte", label: "Samal" },
    { value: "san_isidro_davao_del_norte", label: "San Isidro" },
    { value: "santo_tomas_davao_del_norte", label: "Santo Tomas" },
    { value: "tagum", label: "Tagum" },
    { value: "talaingod", label: "Talaingod" },
  ],
  davao_del_sur: [
    { value: "bansalan", label: "Bansalan" },
    { value: "davao_city", label: "Davao City" },
    { value: "digos", label: "Digos" },
    { value: "hagonoy_davao_del_sur", label: "Hagonoy" },
    { value: "kiblawan", label: "Kiblawan" },
    { value: "magsaysay_davao_del_sur", label: "Magsaysay" },
    { value: "malalag", label: "Malalag" },
    { value: "matanao", label: "Matanao" },
    { value: "padada", label: "Padada" },
    { value: "santa_cruz_davao_del_sur", label: "Santa Cruz" },
    { value: "sulop", label: "Sulop" },
  ],
  davao_occidental: [
    { value: "don_marcelino", label: "Don Marcelino" },
    { value: "jose_abad_santos", label: "Jose Abad Santos" },
    { value: "malita", label: "Malita" },
    { value: "santa_maria_davao_occidental", label: "Santa Maria" },
  ],
  davao_oriental: [
    { value: "baganga", label: "Baganga" },
    { value: "banaybanay", label: "Banaybanay" },
    { value: "boston_davao_oriental", label: "Boston" },
    { value: "caraga_davao_oriental", label: "Caraga" },
    { value: "cateel", label: "Cateel" },
    { value: "governor_generoso", label: "Governor Generoso" },
    { value: "lupon", label: "Lupon" },
    { value: "manay", label: "Manay" },
    { value: "mati", label: "Mati" },
    { value: "san_isidro_davao_oriental", label: "San Isidro" },
    { value: "tarragona", label: "Tarragona" },
  ],
  dinagat_islands: [
    { value: "basilisa", label: "Basilisa" },
    { value: "cagdianao", label: "Cagdianao" },
    { value: "dinagat", label: "Dinagat" },
    { value: "libjo", label: "Libjo" },
    { value: "loreto", label: "Loreto" },
    { value: "san_jose_dinagat_islands", label: "San Jose" },
    { value: "tubajon", label: "Tubajon" },
  ],
  eastern_samar: [
    { value: "arteche", label: "Arteche" },
    { value: "balangiga", label: "Balangiga" },
    { value: "balangkayan", label: "Balangkayan" },
    { value: "borongan", label: "Borongan" },
    { value: "can_avid", label: "Can-avid" },
    { value: "dolores_eastern_samar", label: "Dolores" },
    { value: "general_macarthur", label: "General MacArthur" },
    { value: "giporlos", label: "Giporlos" },
    { value: "guiuan", label: "Guiuan" },
    { value: "hernani", label: "Hernani" },
    { value: "jipapad", label: "Jipapad" },
    { value: "lawaan", label: "Lawaan" },
    { value: "llorente", label: "Llorente" },
    { value: "maslog", label: "Maslog" },
    { value: "maydolong", label: "Maydolong" },
    { value: "mercedes_eastern_samar", label: "Mercedes" },
    { value: "oras", label: "Oras" },
    { value: "quinapondan", label: "Quinapondan" },
    { value: "salcedo_eastern_samar", label: "Salcedo" },
    { value: "san_julian", label: "San Julian" },
    { value: "san_policarpo", label: "San Policarpo" },
    { value: "sulat", label: "Sulat" },
    { value: "taft", label: "Taft" },
  ],
  guimaras: [
    { value: "buenavista", label: "Buenavista" },
    { value: "jordan_guimaras", label: "Jordan" },
    { value: "nueva_valencia", label: "Nueva Valencia" },
    { value: "san_lorenzo", label: "San Lorenzo" },
    { value: "sibunag", label: "Sibunag" },
  ],
  ifugao: [
    { value: "aguinaldo", label: "Aguinaldo" },
    { value: "alfonso_lista", label: "Alfonso Lista" },
    { value: "asipulo", label: "Asipulo" },
    { value: "banaue", label: "Banaue" },
    { value: "hingyon", label: "Hingyon" },
    { value: "hungduan", label: "Hungduan" },
    { value: "kiangan", label: "Kiangan" },
    { value: "lagawe", label: "Lagawe" },
    { value: "lamut", label: "Lamut" },
    { value: "mayoyao", label: "Mayoyao" },
    { value: "tinoc", label: "Tinoc" },
  ],
  ilocos_norte: [
    { value: "adams", label: "Adams" },
    { value: "bacarra", label: "Bacarra" },
    { value: "badoc", label: "Badoc" },
    { value: "bangui", label: "Bangui" },
    { value: "banna", label: "Banna" },
    { value: "batac", label: "Batac" },
    { value: "burgos_ilocos_norte", label: "Burgos" },
    { value: "carasi", label: "Carasi" },
    { value: "currimao", label: "Currimao" },
    { value: "dingras", label: "Dingras" },
    { value: "dumalneg", label: "Dumalneg" },
    { value: "laoag", label: "Laoag" },
    { value: "marcos_ilocos_norte", label: "Marcos" },
    { value: "nueva_era", label: "Nueva Era" },
    { value: "pagudpud", label: "Pagudpud" },
    { value: "paoay", label: "Paoay" },
    { value: "pasuquin", label: "Pasuquin" },
    { value: "piddig", label: "Piddig" },
    { value: "pinili", label: "Pinili" },
    { value: "san_nicolas_ilocos_norte", label: "San Nicolas" },
    { value: "sarrat", label: "Sarrat" },
    { value: "solsona", label: "Solsona" },
    { value: "vintar", label: "Vintar" },
  ],
  ilocos_sur: [
    { value: "alilem", label: "Alilem" },
    { value: "banayoyo", label: "Banayoyo" },
    { value: "bantay", label: "Bantay" },
    { value: "burgos_ilocos_sur", label: "Burgos" },
    { value: "cabugao", label: "Cabugao" },
    { value: "candon", label: "Candon" },
    { value: "caoayan", label: "Caoayan" },
    { value: "cervantes", label: "Cervantes" },
    { value: "galimuyod", label: "Galimuyod" },
    { value: "gregorio_del_pilar", label: "Gregorio del Pilar" },
    { value: "lidlidda", label: "Lidlidda" },
    { value: "magsingal", label: "Magsingal" },
    { value: "nagbukel", label: "Nagbukel" },
    { value: "narvacan", label: "Narvacan" },
    { value: "quirino_ilocos_sur", label: "Quirino" },
    { value: "salcedo_ilocos_sur", label: "Salcedo" },
    { value: "san_emilio", label: "San Emilio" },
    { value: "san_esteban", label: "San Esteban" },
    { value: "san_ildefonso", label: "San Ildefonso" },
    { value: "san_juan_ilocos_sur", label: "San Juan" },
    { value: "san_vicente_ilocos_sur", label: "San Vicente" },
    { value: "santa_catalina_ilocos_sur", label: "Santa Catalina" },
    { value: "santa_cruz_ilocos_sur", label: "Santa Cruz" },
    { value: "santa_lucia_ilocos_sur", label: "Santa Lucia" },
    { value: "santa_maria_ilocos_sur", label: "Santa Maria" },
    { value: "santa_ilocos_sur", label: "Santa" },
    { value: "santiago_ilocos_sur", label: "Santiago" },
    { value: "santo_domingo_ilocos_sur", label: "Santo Domingo" },
    { value: "sigay", label: "Sigay" },
    { value: "sinait", label: "Sinait" },
    { value: "sugpon", label: "Sugpon" },
    { value: "suyo", label: "Suyo" },
    { value: "tagudin", label: "Tagudin" },
    { value: "vigan", label: "Vigan" },
  ],
  iloilo: [
    { value: "ajuy", label: "Ajuy" },
    { value: "alimodian", label: "Alimodian" },
    { value: "anilao", label: "Anilao" },
    { value: "badiangan", label: "Badiangan" },
    { value: "balasan", label: "Balasan" },
    { value: "banate", label: "Banate" },
    { value: "barotac_nuevo", label: "Barotac Nuevo" },
    { value: "barotac_viejo", label: "Barotac Viejo" },
    { value: "batad", label: "Batad" },
    { value: "bingawan", label: "Bingawan" },
    { value: "cabatuan", label: "Cabatuan" },
    { value: "calinog", label: "Calinog" },
    { value: "carles", label: "Carles" },
    { value: "concepcion", label: "Concepcion" },
    { value: "dingle", label: "Dingle" },
    { value: "duenas", label: "Dueñas" },
    { value: "dumangas", label: "Dumangas" },
    { value: "estancia", label: "Estancia" },
    { value: "guimbal", label: "Guimbal" },
    { value: "igbaras", label: "Igbaras" },
    { value: "iloilo_city", label: "Iloilo City" },
    { value: "janiuay", label: "Janiuay" },
    { value: "lambunao", label: "Lambunao" },
    { value: "leganes", label: "Leganes" },
    { value: "lemery", label: "Lemery" },
    { value: "leon", label: "Leon" },
    { value: "maasin", label: "Maasin" },
    { value: "miagao", label: "Miagao" },
    { value: "mina", label: "Mina" },
    { value: "new_lucena", label: "New Lucena" },
    { value: "oton", label: "Oton" },
    { value: "passi", label: "Passi" },
    { value: "pavia", label: "Pavia" },
    { value: "pototan", label: "Pototan" },
    { value: "san_dionisio", label: "San Dionisio" },
    { value: "san_enrique", label: "San Enrique" },
    { value: "san_joaquin", label: "San Joaquin" },
    { value: "san_miguel", label: "San Miguel" },
    { value: "san_rafael", label: "San Rafael" },
    { value: "santa_barbara", label: "Santa Barbara" },
    { value: "sara", label: "Sara" },
    { value: "tigbauan", label: "Tigbauan" },
    { value: "tubungan", label: "Tubungan" },
    { value: "zarraga", label: "Zarraga" },
  ],

  isabela: [
    { value: "alicia", label: "Alicia" },
    { value: "angadanan", label: "Angadanan" },
    { value: "aurora", label: "Aurora" },
    { value: "benito_soliven", label: "Benito Soliven" },
    { value: "burgos", label: "Burgos" },
    { value: "cabagan", label: "Cabagan" },
    { value: "cabatuan", label: "Cabatuan" },
    { value: "cauayan", label: "Cauayan" },
    { value: "cordon", label: "Cordon" },
    { value: "delfin_albano", label: "Delfin Albano" },
    { value: "dinapigue", label: "Dinapigue" },
    { value: "divilacan", label: "Divilacan" },
    { value: "echague", label: "Echague" },
    { value: "gamu", label: "Gamu" },
    { value: "ilagan", label: "Ilagan" },
    { value: "jones", label: "Jones" },
    { value: "luna", label: "Luna" },
    { value: "maconacon", label: "Maconacon" },
    { value: "mallig", label: "Mallig" },
    { value: "naguilian", label: "Naguilian" },
    { value: "palanan", label: "Palanan" },
    { value: "quezon", label: "Quezon" },
    { value: "quirino", label: "Quirino" },
    { value: "ramon", label: "Ramon" },
    { value: "reina_mercedes", label: "Reina Mercedes" },
    { value: "roxas", label: "Roxas" },
    { value: "san_agustin", label: "San Agustin" },
    { value: "san_guillermo", label: "San Guillermo" },
    { value: "san_isidro", label: "San Isidro" },
    { value: "san_manuel", label: "San Manuel" },
    { value: "san_mariano", label: "San Mariano" },
    { value: "san_mateo", label: "San Mateo" },
    { value: "san_pablo", label: "San Pablo" },
    { value: "santa_maria", label: "Santa Maria" },
    { value: "santiago", label: "Santiago" },
    { value: "santo_tomas", label: "Santo Tomas" },
    { value: "tumauini", label: "Tumauini" },
  ],

  kalinga: [
    { value: "balbalan", label: "Balbalan" },
    { value: "lubuagan", label: "Lubuagan" },
    { value: "pasil", label: "Pasil" },
    { value: "pinukpuk", label: "Pinukpuk" },
    { value: "rizal", label: "Rizal" },
    { value: "tabuk", label: "Tabuk" },
    { value: "tanudan", label: "Tanudan" },
    { value: "tinglayan", label: "Tinglayan" },
  ],

  la_union: [
    { value: "agoo", label: "Agoo" },
    { value: "aringay", label: "Aringay" },
    { value: "bacnotan", label: "Bacnotan" },
    { value: "bagulin", label: "Bagulin" },
    { value: "balaoan", label: "Balaoan" },
    { value: "bangar", label: "Bangar" },
    { value: "bauang", label: "Bauang" },
    { value: "burgos", label: "Burgos" },
    { value: "caba", label: "Caba" },
    { value: "luna_la_union", label: "Luna" },
    { value: "naguilian_la_union", label: "Naguilian" },
    { value: "pugo", label: "Pugo" },
    { value: "rosario_la_union", label: "Rosario" },
    { value: "san_fernando", label: "San Fernando" },
    { value: "san_gabriel", label: "San Gabriel" },
    { value: "san_juan_la_union", label: "San Juan" },
    { value: "santo_tomas_la_union", label: "Santo Tomas" },
    { value: "santol", label: "Santol" },
    { value: "sudipen", label: "Sudipen" },
    { value: "tubao", label: "Tubao" },
  ],

  laguna: [
    { value: "alaminos", label: "Alaminos" },
    { value: "bay", label: "Bay" },
    { value: "binan", label: "Biñan" },
    { value: "cabuyao", label: "Cabuyao" },
    { value: "calamba", label: "Calamba" },
    { value: "calauan", label: "Calauan" },
    { value: "cavinti", label: "Cavinti" },
    { value: "famy", label: "Famy" },
    { value: "kalayaan", label: "Kalayaan" },
    { value: "liliw", label: "Liliw" },
    { value: "los_banos", label: "Los Baños" },
    { value: "luisiana", label: "Luisiana" },
    { value: "lumban", label: "Lumban" },
    { value: "mabitac", label: "Mabitac" },
    { value: "magdalena", label: "Magdalena" },
    { value: "majayjay", label: "Majayjay" },
    { value: "nagcarlan", label: "Nagcarlan" },
    { value: "paete", label: "Paete" },
    { value: "pagsanjan", label: "Pagsanjan" },
    { value: "pakil", label: "Pakil" },
    { value: "pangil", label: "Pangil" },
    { value: "pila", label: "Pila" },
    { value: "rizal_laguna", label: "Rizal" },
    { value: "san_pablo", label: "San Pablo" },
    { value: "san_pedro", label: "San Pedro" },
    { value: "santa_cruz", label: "Santa Cruz" },
    { value: "santa_maria_laguna", label: "Santa Maria" },
    { value: "santa_rosa", label: "Santa Rosa" },
    { value: "siniloan", label: "Siniloan" },
    { value: "victoria", label: "Victoria" },
  ],
};
