interface ProvinceOption {
  value: string;
  label: string;
}

export const provinces: ProvinceOption[] = [
  { value: "Abra", label: "Abra" },
  { value: "Agusan del Norte", label: "Agusan del Norte" },
  { value: "Agusan del Sur", label: "Agusan del Sur" },
  { value: "Aklan", label: "Aklan" },
  { value: "Albay", label: "Albay" },
  { value: "Antique", label: "Antique" },
  { value: "Apayao", label: "Apayao" },
  { value: "Aurora", label: "Aurora" },
  { value: "Basilan", label: "Basilan" },
  { value: "Bataan", label: "Bataan" },
  { value: "Batanes", label: "Batanes" },
  { value: "Batangas", label: "Batangas" },
  { value: "Benguet", label: "Benguet" },
  { value: "Biliran", label: "Biliran" },
  { value: "Bohol", label: "Bohol" },
  { value: "Bukidnon", label: "Bukidnon" },
  { value: "Bulacan", label: "Bulacan" },
  { value: "Cagayan", label: "Cagayan" },
  { value: "Camarines Norte", label: "Camarines Norte" },
  { value: "Camarines Sur", label: "Camarines Sur" },
  { value: "Camiguin", label: "Camiguin" },
  { value: "Capiz", label: "Capiz" },
  { value: "Catanduanes", label: "Catanduanes" },
  { value: "Cavite", label: "Cavite" },
  { value: "Cebu", label: "Cebu" },
  { value: "Compostela Valley", label: "Compostela Valley" },
  { value: "Cotabato", label: "Cotabato" },
  { value: "Davao de Oro (Compostela Valley)", label: "Davao de Oro (Compostela Valley)" },
  { value: "Davao del Norte", label: "Davao del Norte" },
  { value: "Davao del Sur", label: "Davao del Sur" },
  { value: "Davao Occidental", label: "Davao Occidental" },
  { value: "Davao Oriental", label: "Davao Oriental" },
  { value: "Dinagat Islands", label: "Dinagat Islands" },
  { value: "Eastern Samar", label: "Eastern Samar" },
  { value: "Guimaras", label: "Guimaras" },
  { value: "Ifugao", label: "Ifugao" },
  { value: "Ilocos Norte", label: "Ilocos Norte" },
  { value: "Ilocos Sur", label: "Ilocos Sur" },
  { value: "Iloilo", label: "Iloilo" },
  { value: "Isabela", label: "Isabela" },
  { value: "Kalinga", label: "Kalinga" },
  { value: "La Union", label: "La Union" },
  { value: "Laguna", label: "Laguna" },
  { value: "Lanao del Norte", label: "Lanao del Norte" },
  { value: "Lanao del Sur", label: "Lanao del Sur" },
  { value: "Leyte", label: "Leyte" },
  { value: "Maguindanao", label: "Maguindanao" },
  { value: "Marinduque", label: "Marinduque" },
  { value: "Masbate", label: "Masbate" },
  { value: "Metro Manila", label: "Metro Manila" },
  { value: "Misamis Occidental", label: "Misamis Occidental" },
  { value: "Misamis Oriental", label: "Misamis Oriental" },
  { value: "Mountain Province", label: "Mountain Province" },
  { value: "Negros Occidental", label: "Negros Occidental" },
  { value: "Negros Oriental", label: "Negros Oriental" },
  { value: "Northern Samar", label: "Northern Samar" },
  { value: "Nueva Ecija", label: "Nueva Ecija" },
  { value: "Nueva Vizcaya", label: "Nueva Vizcaya" },
  { value: "Occidental Mindoro", label: "Occidental Mindoro" },
  { value: "Oriental Mindoro", label: "Oriental Mindoro" },
  { value: "Palawan", label: "Palawan" },
  { value: "Pampanga", label: "Pampanga" },
  { value: "Pangasinan", label: "Pangasinan" },
  { value: "Quezon", label: "Quezon" },
  { value: "Quirino", label: "Quirino" },
  { value: "Rizal", label: "Rizal" },
  { value: "Romblon", label: "Romblon" },
  { value: "Samar", label: "Samar" },
  { value: "Sarangani", label: "Sarangani" },
  { value: "Siquijor", label: "Siquijor" },
  { value: "Sorsogon", label: "Sorsogon" },
  { value: "South Cotabato", label: "South Cotabato" },
  { value: "Southern Leyte", label: "Southern Leyte" },
  { value: "Sultan Kudarat", label: "Sultan Kudarat" },
  { value: "Sulu", label: "Sulu" },
  { value: "Surigao del Norte", label: "Surigao del Norte" },
  { value: "Surigao del Sur", label: "Surigao del Sur" },
  { value: "Tarlac", label: "Tarlac" },
  { value: "Tawi-Tawi", label: "Tawi-Tawi" },
  { value: "Zambales", label: "Zambales" },
  { value: "Zamboanga del Norte", label: "Zamboanga del Norte" },
  { value: "Zamboanga del Sur", label: "Zamboanga del Sur" },
  { value: "Zamboanga Sibugay", label: "Zamboanga Sibugay" },
];

export const provincesTest = [
  { value: "abra", label: "Abra" },
  { value: "agusan_del_norte", label: "Agusan del Norte" },
  { value: "agusan_del_sur", label: "Agusan del Sur" },
  { value: "aklan", label: "Aklan" },
  { value: "albay", label: "Albay" },
  { value: "antique", label: "Antique" },
  { value: "apayao", label: "Apayao" },
  { value: "aurora", label: "Aurora" },
  { value: "basilan", label: "Basilan" },
  { value: "bataan", label: "Bataan" },
  { value: "batanes", label: "Batanes" },
  { value: "batangas", label: "Batangas" },
  { value: "benguet", label: "Benguet" },
  { value: "biliran", label: "Biliran" },
  { value: "bohol", label: "Bohol" },
  { value: "bukidnon", label: "Bukidnon" },
  { value: "bulacan", label: "Bulacan" },
  { value: "cagayan", label: "Cagayan" },
  { value: "camarines_norte", label: "Camarines Norte" },
  { value: "camarines_sur", label: "Camarines Sur" },
  { value: "camiguin", label: "Camiguin" },
  { value: "capiz", label: "Capiz" },
  { value: "catanduanes", label: "Catanduanes" },
  { value: "cavite", label: "Cavite" },
  { value: "cebu", label: "Cebu" },
  { value: "compostela_valley", label: "Compostela Valley" },
  { value: "cotabato", label: "Cotabato" },
  { value: "davao_de_oro", label: "Davao de Oro (Compostela Valley)" },
  { value: "davao_del_norte", label: "Davao del Norte" },
  { value: "davao_del_sur", label: "Davao del Sur" },
  { value: "davao_occidental", label: "Davao Occidental" },
  { value: "davao_oriental", label: "Davao Oriental" },
  { value: "dinagat_islands", label: "Dinagat Islands" },
  { value: "eastern_samar", label: "Eastern Samar" },
  { value: "guimaras", label: "Guimaras" },
  { value: "ifugao", label: "Ifugao" },
  { value: "ilocos_norte", label: "Ilocos Norte" },
  { value: "ilocos_sur", label: "Ilocos Sur" },
  { value: "iloilo", label: "Iloilo" },
  { value: "isabela", label: "Isabela" },
  { value: "kalinga", label: "Kalinga" },
  { value: "la_union", label: "La Union" },
  { value: "laguna", label: "Laguna" },
  { value: "lanao_del_norte", label: "Lanao del Norte" },
  { value: "lanao_del_sur", label: "Lanao del Sur" },
  { value: "leyte", label: "Leyte" },
  { value: "maguindanao", label: "Maguindanao" },
  { value: "marinduque", label: "Marinduque" },
  { value: "masbate", label: "Masbate" },
  { value: "metro_manila", label: "Metro Manila" },
  { value: "misamis_occidental", label: "Misamis Occidental" },
  { value: "misamis_oriental", label: "Misamis Oriental" },
  { value: "mountain_province", label: "Mountain Province" },
  { value: "negros_occidental", label: "Negros Occidental" },
  { value: "negros_oriental", label: "Negros Oriental" },
  { value: "northern_samar", label: "Northern Samar" },
  { value: "nueva_ecija", label: "Nueva Ecija" },
  { value: "nueva_vizcaya", label: "Nueva Vizcaya" },
  { value: "occidental_mindoro", label: "Occidental Mindoro" },
  { value: "oriental_mindoro", label: "Oriental Mindoro" },
  { value: "palawan", label: "Palawan" },
  { value: "pampanga", label: "Pampanga" },
  { value: "pangasinan", label: "Pangasinan" },
  { value: "quezon", label: "Quezon" },
  { value: "quirino", label: "Quirino" },
  { value: "rizal", label: "Rizal" },
  { value: "romblon", label: "Romblon" },
  { value: "samar", label: "Samar" },
  { value: "sarangani", label: "Sarangani" },
  { value: "siquijor", label: "Siquijor" },
  { value: "sorsogon", label: "Sorsogon" },
  { value: "south_cotabato", label: "South Cotabato" },
  { value: "southern_leyte", label: "Southern Leyte" },
  { value: "sultan_kudarat", label: "Sultan Kudarat" },
  { value: "sulu", label: "Sulu" },
  { value: "surigao_del_norte", label: "Surigao del Norte" },
  { value: "surigao_del_sur", label: "Surigao del Sur" },
  { value: "tarlac", label: "Tarlac" },
  { value: "tawi_tawi", label: "Tawi-Tawi" },
  { value: "zambales", label: "Zambales" },
  { value: "zamboanga_del_norte", label: "Zamboanga del Norte" },
  { value: "zamboanga_del_sur", label: "Zamboanga del Sur" },
  { value: "zamboanga_sibugay", label: "Zamboanga Sibugay" },
];

export const municipalities: { [key: string]: { value: string; label: string }[] } = {
  abra: [
    { value: "bangued", label: "Bangued" },
    { value: "boliney", label: "Boliney" },
    { value: "bucay", label: "Bucay" },
    { value: "bucloc", label: "Bucloc" },
    { value: "daguioman", label: "Daguioman" },
    { value: "danglas", label: "Danglas" },
    { value: "dolores", label: "Dolores" },
    { value: "la_paz", label: "La Paz" },
    { value: "lacub", label: "Lacub" },
    { value: "lagangilang", label: "Lagangilang" },
    { value: "lagayan", label: "Lagayan" },
    { value: "langiden", label: "Langiden" },
    { value: "licuan_baay", label: "Licuan-Baay" },
    { value: "luba", label: "Luba" },
    { value: "malibcong", label: "Malibcong" },
    { value: "manabo", label: "Manabo" },
    { value: "penarrubia", label: "Peñarrubia" },
    { value: "pidigan", label: "Pidigan" },
    { value: "pilar", label: "Pilar" },
    { value: "sallapadan", label: "Sallapadan" },
    { value: "san_isidro", label: "San Isidro" },
    { value: "san_juan", label: "San Juan" },
    { value: "san_quintin", label: "San Quintin" },
    { value: "tayum", label: "Tayum" },
    { value: "tineg", label: "Tineg" },
    { value: "tubo", label: "Tubo" },
    { value: "villaviciosa", label: "Villaviciosa" },
  ],
  agusan_del_norte: [
    { value: "cabadbaran", label: "Cabadbaran" },
    { value: "carmen", label: "Carmen" },
    { value: "jabonga", label: "Jabonga" },
    { value: "kitcharao", label: "Kitcharao" },
    { value: "las_nieves", label: "Las Nieves" },
    { value: "magallanes", label: "Magallanes" },
    { value: "nasipit", label: "Nasipit" },
    { value: "remedios_t_romualdez", label: "Remedios T. Romualdez" },
    { value: "santiago", label: "Santiago" },
  ],
  agusan_del_sur: [
    { value: "tubay", label: "Tubay" },
    { value: "bayugan", label: "Bayugan" },
    { value: "bunawan", label: "Bunawan" },
    { value: "esperanza", label: "Esperanza" },
    { value: "la_paz_agusan_del_sur", label: "La Paz" },
    { value: "loreto", label: "Loreto" },
    { value: "prosperidad", label: "Prosperidad" },
    { value: "rosario", label: "Rosario" },
    { value: "san_francisco", label: "San Francisco" },
    { value: "san_luis", label: "San Luis" },
    { value: "santa_josefa", label: "Santa Josefa" },
    { value: "sibagat", label: "Sibagat" },
    { value: "talacogon", label: "Talacogon" },
    { value: "trento", label: "Trento" },
    { value: "veruela", label: "Veruela" },
  ],
  aklan: [
    { value: "altavas", label: "Altavas" },
    { value: "balete", label: "Balete" },
    { value: "banga", label: "Banga" },
    { value: "batan", label: "Batan" },
    { value: "buruanga", label: "Buruanga" },
    { value: "ibajay", label: "Ibajay" },
    { value: "kalibo", label: "Kalibo" },
    { value: "lezo", label: "Lezo" },
    { value: "libacao", label: "Libacao" },
    { value: "madalag", label: "Madalag" },
    { value: "makato", label: "Makato" },
    { value: "malay", label: "Malay" },
    { value: "malinao", label: "Malinao" },
    { value: "nabas", label: "Nabas" },
    { value: "new_washington", label: "New Washington" },
    { value: "numancia", label: "Numancia" },
    { value: "tangalan", label: "Tangalan" },
  ],
  albay: [
    { value: "bacacay", label: "Bacacay" },
    { value: "camalig", label: "Camalig" },
    { value: "daraga", label: "Daraga" },
    { value: "guinobatan", label: "Guinobatan" },
    { value: "jovellar", label: "Jovellar" },
    { value: "legazpi", label: "Legazpi" },
    { value: "libon", label: "Libon" },
    { value: "ligao", label: "Ligao" },
    { value: "malilipot", label: "Malilipot" },
    { value: "malinao_albay", label: "Malinao" },
    { value: "manito", label: "Manito" },
    { value: "oas", label: "Oas" },
    { value: "pio_duran", label: "Pio Duran" },
    { value: "polangui", label: "Polangui" },
    { value: "rapu_rapu", label: "Rapu-Rapu" },
    { value: "santo_domingo", label: "Santo Domingo" },
    { value: "tabaco", label: "Tabaco" },
    { value: "tiwi", label: "Tiwi" },
  ],
  antique: [
    { value: "anini_y", label: "Anini-y" },
    { value: "barbaza", label: "Barbaza" },
    { value: "belison", label: "Belison" },
    { value: "bugasong", label: "Bugasong" },
    { value: "caluya", label: "Caluya" },
    { value: "culasi", label: "Culasi" },
    { value: "hamtic", label: "Hamtic" },
    { value: "laua_an", label: "Laua-an" },
    { value: "libertad", label: "Libertad" },
    { value: "pandan", label: "Pandan" },
    { value: "patnongon", label: "Patnongon" },
    { value: "san_jose_de_buenavista", label: "San Jose de Buenavista" },
    { value: "san_remigio", label: "San Remigio" },
    { value: "sebaste", label: "Sebaste" },
    { value: "sibalom", label: "Sibalom" },
    { value: "tibiao", label: "Tibiao" },
    { value: "tobias_fornier", label: "Tobias Fornier" },
    { value: "valderrama", label: "Valderrama" },
  ],
  apayao: [
    { value: "calanasan", label: "Calanasan" },
    { value: "conner", label: "Conner" },
    { value: "flora", label: "Flora" },
    { value: "kabugao", label: "Kabugao" },
    { value: "luna", label: "Luna" },
    { value: "pudtol", label: "Pudtol" },
    { value: "santa_marcela", label: "Santa Marcela" },
  ],
  aurora: [
    { value: "baler", label: "Baler" },
    { value: "casiguran", label: "Casiguran" },
    { value: "dilasag", label: "Dilasag" },
    { value: "dinalungan", label: "Dinalungan" },
    { value: "dingalan", label: "Dingalan" },
    { value: "dipaculao", label: "Dipaculao" },
    { value: "maria_aurora", label: "Maria Aurora" },
    { value: "san_luis", label: "San Luis" },
  ],
  basilan: [
    { value: "akbar", label: "Akbar" },
    { value: "al_barka", label: "Al-Barka" },
    { value: "hadji_mohammad_ajul", label: "Hadji Mohammad Ajul" },
    { value: "hadji_muhtamad", label: "Hadji Muhtamad" },
    { value: "isabela", label: "Isabela" },
    { value: "lamitan", label: "Lamitan" },
    { value: "lantawan", label: "Lantawan" },
    { value: "maluso", label: "Maluso" },
    { value: "sumisip", label: "Sumisip" },
    { value: "tabuan_lasa", label: "Tabuan-Lasa" },
    { value: "tipo_tipo", label: "Tipo-Tipo" },
    { value: "tuburan", label: "Tuburan" },
    { value: "ungkaya_pukan", label: "Ungkaya Pukan" },
  ],
  bataan: [
    { value: "abucay", label: "Abucay" },
    { value: "bagac", label: "Bagac" },
    { value: "balanga", label: "Balanga" },
    { value: "dinalupihan", label: "Dinalupihan" },
    { value: "hermosa", label: "Hermosa" },
    { value: "limay", label: "Limay" },
    { value: "mariveles", label: "Mariveles" },
    { value: "morong", label: "Morong" },
    { value: "orani", label: "Orani" },
    { value: "orion", label: "Orion" },
    { value: "pilar", label: "Pilar" },
    { value: "samal", label: "Samal" },
  ],
  batanes: [
    { value: "basco", label: "Basco" },
    { value: "itbayat", label: "Itbayat" },
    { value: "ivana", label: "Ivana" },
    { value: "mahatao", label: "Mahatao" },
    { value: "sabtang", label: "Sabtang" },
    { value: "uyugan", label: "Uyugan" },
  ],
  batangas: [
    { value: "agoncillo", label: "Agoncillo" },
    { value: "alitagtag", label: "Alitagtag" },
    { value: "balayan", label: "Balayan" },
    { value: "balete_batangas", label: "Balete" },
    { value: "batangas_city", label: "Batangas City" },
    { value: "bauan", label: "Bauan" },
    { value: "calaca", label: "Calaca" },
    { value: "calatagan", label: "Calatagan" },
    { value: "cuenca", label: "Cuenca" },
    { value: "ibaan", label: "Ibaan" },
    { value: "laurel", label: "Laurel" },
    { value: "lemery", label: "Lemery" },
    { value: "lian", label: "Lian" },
    { value: "lipa", label: "Lipa" },
    { value: "lobo", label: "Lobo" },
    { value: "mabini_batangas", label: "Mabini" },
    { value: "malvar", label: "Malvar" },
    { value: "mataasnakahoy", label: "Mataasnakahoy" },
    { value: "nasugbu", label: "Nasugbu" },
    { value: "padre_garcia", label: "Padre Garcia" },
    { value: "rosario_batangas", label: "Rosario" },
    { value: "san_jose_batangas", label: "San Jose" },
    { value: "san_juan_batangas", label: "San Juan" },
    { value: "san_luis_batangas", label: "San Luis" },
    { value: "san_nicolas_batangas", label: "San Nicolas" },
    { value: "san_pascual_batangas", label: "San Pascual" },
    { value: "santa_teresita_batangas", label: "Santa Teresita" },
    { value: "santo_tomas_batangas", label: "Santo Tomas" },
    { value: "taal", label: "Taal" },
    { value: "talisay_batangas", label: "Talisay" },
    { value: "tanauan", label: "Tanauan" },
    { value: "taysan", label: "Taysan" },
    { value: "tingloy", label: "Tingloy" },
    { value: "tuy", label: "Tuy" },
  ],
  benguet: [
    { value: "atok", label: "Atok" },
    { value: "baguio", label: "Baguio" },
    { value: "bakun", label: "Bakun" },
    { value: "bokod", label: "Bokod" },
    { value: "buguias", label: "Buguias" },
    { value: "itogon", label: "Itogon" },
    { value: "kabayan", label: "Kabayan" },
    { value: "kapangan", label: "Kapangan" },
    { value: "kibungan", label: "Kibungan" },
    { value: "la_trinidad", label: "La Trinidad" },
    { value: "mankayan", label: "Mankayan" },
    { value: "sablan", label: "Sablan" },
    { value: "tuba", label: "Tuba" },
    { value: "tublay", label: "Tublay" },
  ],
  biliran: [
    { value: "almeria", label: "Almeria" },
    { value: "biliran", label: "Biliran" },
    { value: "cabucgayan", label: "Cabucgayan" },
    { value: "caibiran", label: "Caibiran" },
    { value: "culaba", label: "Culaba" },
    { value: "kawayan", label: "Kawayan" },
    { value: "maripipi", label: "Maripipi" },
    { value: "naval", label: "Naval" },
  ],
  bohol: [
    { value: "alburquerque", label: "Alburquerque" },
    { value: "alicia", label: "Alicia" },
    { value: "anda", label: "Anda" },
    { value: "antequera", label: "Antequera" },
    { value: "baclayon", label: "Baclayon" },
    { value: "balilihan", label: "Balilihan" },
    { value: "batuan", label: "Batuan" },
    { value: "bien_unido", label: "Bien Unido" },
    { value: "bilar", label: "Bilar" },
    { value: "buenavista_bohol", label: "Buenavista" },
    { value: "calape", label: "Calape" },
    { value: "candijay", label: "Candijay" },
    { value: "carmen_bohol", label: "Carmen" },
    { value: "catigbian", label: "Catigbian" },
    { value: "clarin_bohol", label: "Clarin" },
    { value: "corella", label: "Corella" },
    { value: "cortes_bohol", label: "Cortes" },
    { value: "dagohoy", label: "Dagohoy" },
    { value: "danao_bohol", label: "Danao" },
    { value: "dauis", label: "Dauis" },
    { value: "dimiao", label: "Dimiao" },
    { value: "duero", label: "Duero" },
    { value: "garcia_hernandez", label: "Garcia Hernandez" },
    { value: "getafe", label: "Getafe" },
    { value: "guindulman", label: "Guindulman" },
    { value: "inabanga", label: "Inabanga" },
    { value: "jagna", label: "Jagna" },
    { value: "lila", label: "Lila" },
    { value: "loay", label: "Loay" },
    { value: "loboc", label: "Loboc" },
    { value: "loon", label: "Loon" },
    { value: "mabini_bohol", label: "Mabini" },
    { value: "maribojoc", label: "Maribojoc" },
    { value: "panglao", label: "Panglao" },
    { value: "pilar_bohol", label: "Pilar" },
    { value: "president_carlos_p_garcia", label: "President Carlos P. Garcia" },
    { value: "sagbayan", label: "Sagbayan" },
    { value: "san_isidro_bohol", label: "San Isidro" },
    { value: "san_miguel_bohol", label: "San Miguel" },
    { value: "sevilla", label: "Sevilla" },
    { value: "sierra_bullones", label: "Sierra Bullones" },
    { value: "sikatuna", label: "Sikatuna" },
    { value: "tagbilaran", label: "Tagbilaran" },
    { value: "talibon", label: "Talibon" },
    { value: "trinidad_bohol", label: "Trinidad" },
    { value: "tubigon", label: "Tubigon" },
    { value: "ubay", label: "Ubay" },
    { value: "valencia_bohol", label: "Valencia" },
  ],
  bukidnon: [
    { value: "baungon", label: "Baungon" },
    { value: "cabanglasan", label: "Cabanglasan" },
    { value: "damulog", label: "Damulog" },
    { value: "dangcagan", label: "Dangcagan" },
    { value: "don_carlos", label: "Don Carlos" },
    { value: "impasugong", label: "Impasugong" },
    { value: "kadingilan", label: "Kadingilan" },
    { value: "kalilangan", label: "Kalilangan" },
    { value: "kibawe", label: "Kibawe" },
    { value: "kitaotao", label: "Kitaotao" },
    { value: "lantapan", label: "Lantapan" },
    { value: "libona", label: "Libona" },
    { value: "malaybalay", label: "Malaybalay" },
    { value: "malitbog", label: "Malitbog" },
    { value: "manolo_fortich", label: "Manolo Fortich" },
    { value: "maramag", label: "Maramag" },
    { value: "pangantucan", label: "Pangantucan" },
    { value: "quezon_bukidnon", label: "Quezon" },
    { value: "san_fernando_bukidnon", label: "San Fernando" },
    { value: "sumilao", label: "Sumilao" },
    { value: "talakag", label: "Talakag" },
    { value: "valencia_bukidnon", label: "Valencia" },
  ],
  bulacan: [
    { value: "angat", label: "Angat" },
    { value: "balagtas", label: "Balagtas" },
    { value: "baliwag", label: "Baliwag" },
    { value: "bocaue", label: "Bocaue" },
    { value: "bulakan", label: "Bulakan" },
    { value: "bustos", label: "Bustos" },
    { value: "calumpit", label: "Calumpit" },
    { value: "dona_remedios_trinidad", label: "Doña Remedios Trinidad" },
    { value: "guiguinto", label: "Guiguinto" },
    { value: "hagonoy", label: "Hagonoy" },
    { value: "malolos", label: "Malolos" },
    { value: "marilao", label: "Marilao" },
    { value: "meycauayan", label: "Meycauayan" },
    { value: "norzagaray", label: "Norzagaray" },
    { value: "obando", label: "Obando" },
    { value: "pandi", label: "Pandi" },
    { value: "paombong", label: "Paombong" },
    { value: "plaridel_bulacan", label: "Plaridel" },
    { value: "pulilan", label: "Pulilan" },
    { value: "san_ildefonso", label: "San Ildefonso" },
    { value: "san_jose_del_monte", label: "San Jose del Monte" },
    { value: "san_miguel_bulacan", label: "San Miguel" },
    { value: "san_rafael", label: "San Rafael" },
    { value: "santa_maria_bulacan", label: "Santa Maria" },
  ],
  cagayan: [
    { value: "abulug", label: "Abulug" },
    { value: "alcala", label: "Alcala" },
    { value: "allacapan", label: "Allacapan" },
    { value: "amulung", label: "Amulung" },
    { value: "aparri", label: "Aparri" },
    { value: "baggao", label: "Baggao" },
    { value: "ballesteros", label: "Ballesteros" },
    { value: "buguey", label: "Buguey" },
    { value: "calayan", label: "Calayan" },
    { value: "camalaniugan", label: "Camalaniugan" },
    { value: "claveria", label: "Claveria" },
    { value: "enrile", label: "Enrile" },
    { value: "gattaran", label: "Gattaran" },
    { value: "gonzaga", label: "Gonzaga" },
    { value: "iguig", label: "Iguig" },
    { value: "lal-lo", label: "Lal-lo" },
    { value: "lasam", label: "Lasam" },
    { value: "pamplona", label: "Pamplona" },
    { value: "penablanca", label: "Peñablanca" },
    { value: "piat", label: "Piat" },
    { value: "rizal", label: "Rizal" },
    { value: "sanchez-mira", label: "Sanchez-Mira" },
    { value: "santa_ana", label: "Santa Ana" },
    { value: "santa_praxedes", label: "Santa Praxedes" },
    { value: "santa_teresita", label: "Santa Teresita" },
    { value: "santo_nino", label: "Santo Niño" },
    { value: "solana", label: "Solana" },
    { value: "tuao", label: "Tuao" },
    { value: "tuguegarao", label: "Tuguegarao" },
  ],
  camarines_norte: [
    { value: "basud", label: "Basud" },
    { value: "capalonga", label: "Capalonga" },
    { value: "daet", label: "Daet" },
    { value: "jose_panganiban", label: "Jose Panganiban" },
    { value: "labo", label: "Labo" },
    { value: "mercedes", label: "Mercedes" },
    { value: "paracale", label: "Paracale" },
    { value: "san_lorenzo_ruiz", label: "San Lorenzo Ruiz" },
    { value: "san_vicente", label: "San Vicente" },
    { value: "santa_elena", label: "Santa Elena" },
    { value: "talisay", label: "Talisay" },
    { value: "vinzons", label: "Vinzons" },
  ],
  camarines_sur: [
    { value: "baao", label: "Baao" },
    { value: "balatan", label: "Balatan" },
    { value: "bato", label: "Bato" },
    { value: "bombon", label: "Bombon" },
    { value: "buhi", label: "Buhi" },
    { value: "bula", label: "Bula" },
    { value: "cabusao", label: "Cabusao" },
    { value: "calabanga", label: "Calabanga" },
    { value: "camaligan", label: "Camaligan" },
    { value: "canaman", label: "Canaman" },
    { value: "caramoan", label: "Caramoan" },
    { value: "del_gallego", label: "Del Gallego" },
    { value: "gainza", label: "Gainza" },
    { value: "garchitorena", label: "Garchitorena" },
    { value: "goa", label: "Goa" },
    { value: "iriga", label: "Iriga" },
    { value: "lagonoy", label: "Lagonoy" },
    { value: "libmanan", label: "Libmanan" },
    { value: "lupi", label: "Lupi" },
    { value: "magarao", label: "Magarao" },
    { value: "milaor", label: "Milaor" },
    { value: "minalabac", label: "Minalabac" },
    { value: "nabua", label: "Nabua" },
    { value: "naga", label: "Naga" },
    { value: "ocampo", label: "Ocampo" },
    { value: "pamplona_camsur", label: "Pamplona" },
    { value: "pasacao", label: "Pasacao" },
    { value: "pili", label: "Pili" },
    { value: "presentacion", label: "Presentacion" },
    { value: "ragay", label: "Ragay" },
    { value: "sagnay", label: "Sagñay" },
    { value: "san_fernando_camsur", label: "San Fernando" },
    { value: "san_jose_camsur", label: "San Jose" },
    { value: "sipocot", label: "Sipocot" },
    { value: "siruma", label: "Siruma" },
    { value: "tigaon", label: "Tigaon" },
    { value: "tinambac", label: "Tinambac" },
  ],
  camiguin: [
    { value: "catarman", label: "Catarman" },
    { value: "guinsiliban", label: "Guinsiliban" },
    { value: "mahinog", label: "Mahinog" },
    { value: "mambajao", label: "Mambajao" },
    { value: "sagay_camiguin", label: "Sagay" },
  ],
  capiz: [
    { value: "cuartero", label: "Cuartero" },
    { value: "dao", label: "Dao" },
    { value: "dumalag", label: "Dumalag" },
    { value: "dumarao", label: "Dumarao" },
    { value: "ivisan", label: "Ivisan" },
    { value: "jamindan", label: "Jamindan" },
    { value: "maayon", label: "Ma-ayon" },
    { value: "mambusao", label: "Mambusao" },
    { value: "panay", label: "Panay" },
    { value: "panitan", label: "Panitan" },
    { value: "pilar_capiz", label: "Pilar" },
    { value: "pontevedra", label: "Pontevedra" },
    { value: "president_roxas_capiz", label: "President Roxas" },
    { value: "sapian", label: "Sapian" },
    { value: "sigma", label: "Sigma" },
    { value: "tapaz", label: "Tapaz" },
  ],
  catanduanes: [
    { value: "bagamanoc", label: "Bagamanoc" },
    { value: "baras", label: "Baras" },
    { value: "bato_catanduanes", label: "Bato" },
    { value: "caramoran", label: "Caramoran" },
    { value: "gigmoto", label: "Gigmoto" },
    { value: "pandan_catanduanes", label: "Pandan" },
    { value: "panganiban", label: "Panganiban" },
    { value: "san_andres_catanduanes", label: "San Andres" },
    { value: "san_miguel_catanduanes", label: "San Miguel" },
    { value: "viga", label: "Viga" },
    { value: "virac", label: "Virac" },
  ],
  cavite: [
    { value: "alfonso", label: "Alfonso" },
    { value: "amadeo", label: "Amadeo" },
    { value: "bacoor", label: "Bacoor" },
    { value: "carmona", label: "Carmona" },
    { value: "cavite_city", label: "Cavite City" },
    { value: "dasmarinas", label: "Dasmariñas" },
    { value: "general_emilio_aguinaldo", label: "General Emilio Aguinaldo" },
    { value: "general_mariano_alvarez", label: "General Mariano Alvarez" },
    { value: "general_trias", label: "General Trias" },
    { value: "imus", label: "Imus" },
    { value: "indang", label: "Indang" },
    { value: "kawit", label: "Kawit" },
    { value: "magallanes", label: "Magallanes" },
    { value: "maragondon", label: "Maragondon" },
    { value: "mendez", label: "Mendez" },
    { value: "naic", label: "Naic" },
    { value: "noveleta", label: "Noveleta" },
    { value: "rosario_cavite", label: "Rosario" },
    { value: "silang", label: "Silang" },
    { value: "tagaytay", label: "Tagaytay" },
    { value: "tanza", label: "Tanza" },
    { value: "ternate", label: "Ternate" },
    { value: "trece_martires", label: "Trece Martires" },
  ],
  davao_de_oro: [
    { value: "compostela_davao_de_oro", label: "Compostela" },
    { value: "laak", label: "Laak" },
    { value: "mabini_davao_de_oro", label: "Mabini" },
    { value: "maco", label: "Maco" },
    { value: "maragusan", label: "Maragusan" },
    { value: "mawab", label: "Mawab" },
    { value: "monkayo", label: "Monkayo" },
    { value: "montevista", label: "Montevista" },
    { value: "nabunturan", label: "Nabunturan" },
    { value: "new_bataan", label: "New Bataan" },
    { value: "pantukan", label: "Pantukan" },
  ],
  davao_del_norte: [
    { value: "asuncion", label: "Asuncion" },
    { value: "braulio_e_dujali", label: "Braulio E. Dujali" },
    { value: "carmen_davao_del_norte", label: "Carmen" },
    { value: "kapalong", label: "Kapalong" },
    { value: "new_corella", label: "New Corella" },
    { value: "panabo", label: "Panabo" },
    { value: "samal_davao_del_norte", label: "Samal" },
    { value: "san_isidro_davao_del_norte", label: "San Isidro" },
    { value: "santo_tomas_davao_del_norte", label: "Santo Tomas" },
    { value: "tagum", label: "Tagum" },
    { value: "talaingod", label: "Talaingod" },
  ],
  davao_del_sur: [
    { value: "bansalan", label: "Bansalan" },
    { value: "davao_city", label: "Davao City" },
    { value: "digos", label: "Digos" },
    { value: "hagonoy_davao_del_sur", label: "Hagonoy" },
    { value: "kiblawan", label: "Kiblawan" },
    { value: "magsaysay_davao_del_sur", label: "Magsaysay" },
    { value: "malalag", label: "Malalag" },
    { value: "matanao", label: "Matanao" },
    { value: "padada", label: "Padada" },
    { value: "santa_cruz_davao_del_sur", label: "Santa Cruz" },
    { value: "sulop", label: "Sulop" },
  ],
  davao_occidental: [
    { value: "don_marcelino", label: "Don Marcelino" },
    { value: "jose_abad_santos", label: "Jose Abad Santos" },
    { value: "malita", label: "Malita" },
    { value: "santa_maria_davao_occidental", label: "Santa Maria" },
  ],
  davao_oriental: [
    { value: "baganga", label: "Baganga" },
    { value: "banaybanay", label: "Banaybanay" },
    { value: "boston_davao_oriental", label: "Boston" },
    { value: "caraga_davao_oriental", label: "Caraga" },
    { value: "cateel", label: "Cateel" },
    { value: "governor_generoso", label: "Governor Generoso" },
    { value: "lupon", label: "Lupon" },
    { value: "manay", label: "Manay" },
    { value: "mati", label: "Mati" },
    { value: "san_isidro_davao_oriental", label: "San Isidro" },
    { value: "tarragona", label: "Tarragona" },
  ],
  dinagat_islands: [
    { value: "basilisa", label: "Basilisa" },
    { value: "cagdianao", label: "Cagdianao" },
    { value: "dinagat", label: "Dinagat" },
    { value: "libjo", label: "Libjo" },
    { value: "loreto", label: "Loreto" },
    { value: "san_jose_dinagat_islands", label: "San Jose" },
    { value: "tubajon", label: "Tubajon" },
  ],
  eastern_samar: [
    { value: "arteche", label: "Arteche" },
    { value: "balangiga", label: "Balangiga" },
    { value: "balangkayan", label: "Balangkayan" },
    { value: "borongan", label: "Borongan" },
    { value: "can_avid", label: "Can-avid" },
    { value: "dolores_eastern_samar", label: "Dolores" },
    { value: "general_macarthur", label: "General MacArthur" },
    { value: "giporlos", label: "Giporlos" },
    { value: "guiuan", label: "Guiuan" },
    { value: "hernani", label: "Hernani" },
    { value: "jipapad", label: "Jipapad" },
    { value: "lawaan", label: "Lawaan" },
    { value: "llorente", label: "Llorente" },
    { value: "maslog", label: "Maslog" },
    { value: "maydolong", label: "Maydolong" },
    { value: "mercedes_eastern_samar", label: "Mercedes" },
    { value: "oras", label: "Oras" },
    { value: "quinapondan", label: "Quinapondan" },
    { value: "salcedo_eastern_samar", label: "Salcedo" },
    { value: "san_julian", label: "San Julian" },
    { value: "san_policarpo", label: "San Policarpo" },
    { value: "sulat", label: "Sulat" },
    { value: "taft", label: "Taft" },
  ],
  guimaras: [
    { value: "buenavista", label: "Buenavista" },
    { value: "jordan_guimaras", label: "Jordan" },
    { value: "nueva_valencia", label: "Nueva Valencia" },
    { value: "san_lorenzo", label: "San Lorenzo" },
    { value: "sibunag", label: "Sibunag" },
  ],
  ifugao: [
    { value: "aguinaldo", label: "Aguinaldo" },
    { value: "alfonso_lista", label: "Alfonso Lista" },
    { value: "asipulo", label: "Asipulo" },
    { value: "banaue", label: "Banaue" },
    { value: "hingyon", label: "Hingyon" },
    { value: "hungduan", label: "Hungduan" },
    { value: "kiangan", label: "Kiangan" },
    { value: "lagawe", label: "Lagawe" },
    { value: "lamut", label: "Lamut" },
    { value: "mayoyao", label: "Mayoyao" },
    { value: "tinoc", label: "Tinoc" },
  ],
  ilocos_norte: [
    { value: "adams", label: "Adams" },
    { value: "bacarra", label: "Bacarra" },
    { value: "badoc", label: "Badoc" },
    { value: "bangui", label: "Bangui" },
    { value: "banna", label: "Banna" },
    { value: "batac", label: "Batac" },
    { value: "burgos_ilocos_norte", label: "Burgos" },
    { value: "carasi", label: "Carasi" },
    { value: "currimao", label: "Currimao" },
    { value: "dingras", label: "Dingras" },
    { value: "dumalneg", label: "Dumalneg" },
    { value: "laoag", label: "Laoag" },
    { value: "marcos_ilocos_norte", label: "Marcos" },
    { value: "nueva_era", label: "Nueva Era" },
    { value: "pagudpud", label: "Pagudpud" },
    { value: "paoay", label: "Paoay" },
    { value: "pasuquin", label: "Pasuquin" },
    { value: "piddig", label: "Piddig" },
    { value: "pinili", label: "Pinili" },
    { value: "san_nicolas_ilocos_norte", label: "San Nicolas" },
    { value: "sarrat", label: "Sarrat" },
    { value: "solsona", label: "Solsona" },
    { value: "vintar", label: "Vintar" },
  ],
  ilocos_sur: [
    { value: "alilem", label: "Alilem" },
    { value: "banayoyo", label: "Banayoyo" },
    { value: "bantay", label: "Bantay" },
    { value: "burgos_ilocos_sur", label: "Burgos" },
    { value: "cabugao", label: "Cabugao" },
    { value: "candon", label: "Candon" },
    { value: "caoayan", label: "Caoayan" },
    { value: "cervantes", label: "Cervantes" },
    { value: "galimuyod", label: "Galimuyod" },
    { value: "gregorio_del_pilar", label: "Gregorio del Pilar" },
    { value: "lidlidda", label: "Lidlidda" },
    { value: "magsingal", label: "Magsingal" },
    { value: "nagbukel", label: "Nagbukel" },
    { value: "narvacan", label: "Narvacan" },
    { value: "quirino_ilocos_sur", label: "Quirino" },
    { value: "salcedo_ilocos_sur", label: "Salcedo" },
    { value: "san_emilio", label: "San Emilio" },
    { value: "san_esteban", label: "San Esteban" },
    { value: "san_ildefonso", label: "San Ildefonso" },
    { value: "san_juan_ilocos_sur", label: "San Juan" },
    { value: "san_vicente_ilocos_sur", label: "San Vicente" },
    { value: "santa_catalina_ilocos_sur", label: "Santa Catalina" },
    { value: "santa_cruz_ilocos_sur", label: "Santa Cruz" },
    { value: "santa_lucia_ilocos_sur", label: "Santa Lucia" },
    { value: "santa_maria_ilocos_sur", label: "Santa Maria" },
    { value: "santa_ilocos_sur", label: "Santa" },
    { value: "santiago_ilocos_sur", label: "Santiago" },
    { value: "santo_domingo_ilocos_sur", label: "Santo Domingo" },
    { value: "sigay", label: "Sigay" },
    { value: "sinait", label: "Sinait" },
    { value: "sugpon", label: "Sugpon" },
    { value: "suyo", label: "Suyo" },
    { value: "tagudin", label: "Tagudin" },
    { value: "vigan", label: "Vigan" },
  ],
  iloilo: [
    { value: "ajuy", label: "Ajuy" },
    { value: "alimodian", label: "Alimodian" },
    { value: "anilao", label: "Anilao" },
    { value: "badiangan", label: "Badiangan" },
    { value: "balasan", label: "Balasan" },
    { value: "banate", label: "Banate" },
    { value: "barotac_nuevo", label: "Barotac Nuevo" },
    { value: "barotac_viejo", label: "Barotac Viejo" },
    { value: "batad", label: "Batad" },
    { value: "bingawan", label: "Bingawan" },
    { value: "cabatuan", label: "Cabatuan" },
    { value: "calinog", label: "Calinog" },
    { value: "carles", label: "Carles" },
    { value: "concepcion", label: "Concepcion" },
    { value: "dingle", label: "Dingle" },
    { value: "duenas", label: "Dueñas" },
    { value: "dumangas", label: "Dumangas" },
    { value: "estancia", label: "Estancia" },
    { value: "guimbal", label: "Guimbal" },
    { value: "igbaras", label: "Igbaras" },
    { value: "iloilo_city", label: "Iloilo City" },
    { value: "janiuay", label: "Janiuay" },
    { value: "lambunao", label: "Lambunao" },
    { value: "leganes", label: "Leganes" },
    { value: "lemery", label: "Lemery" },
    { value: "leon", label: "Leon" },
    { value: "maasin", label: "Maasin" },
    { value: "miagao", label: "Miagao" },
    { value: "mina", label: "Mina" },
    { value: "new_lucena", label: "New Lucena" },
    { value: "oton", label: "Oton" },
    { value: "passi", label: "Passi" },
    { value: "pavia", label: "Pavia" },
    { value: "pototan", label: "Pototan" },
    { value: "san_dionisio", label: "San Dionisio" },
    { value: "san_enrique", label: "San Enrique" },
    { value: "san_joaquin", label: "San Joaquin" },
    { value: "san_miguel", label: "San Miguel" },
    { value: "san_rafael", label: "San Rafael" },
    { value: "santa_barbara", label: "Santa Barbara" },
    { value: "sara", label: "Sara" },
    { value: "tigbauan", label: "Tigbauan" },
    { value: "tubungan", label: "Tubungan" },
    { value: "zarraga", label: "Zarraga" },
  ],

  isabela: [
    { value: "alicia", label: "Alicia" },
    { value: "angadanan", label: "Angadanan" },
    { value: "aurora", label: "Aurora" },
    { value: "benito_soliven", label: "Benito Soliven" },
    { value: "burgos", label: "Burgos" },
    { value: "cabagan", label: "Cabagan" },
    { value: "cabatuan", label: "Cabatuan" },
    { value: "cauayan", label: "Cauayan" },
    { value: "cordon", label: "Cordon" },
    { value: "delfin_albano", label: "Delfin Albano" },
    { value: "dinapigue", label: "Dinapigue" },
    { value: "divilacan", label: "Divilacan" },
    { value: "echague", label: "Echague" },
    { value: "gamu", label: "Gamu" },
    { value: "ilagan", label: "Ilagan" },
    { value: "jones", label: "Jones" },
    { value: "luna", label: "Luna" },
    { value: "maconacon", label: "Maconacon" },
    { value: "mallig", label: "Mallig" },
    { value: "naguilian", label: "Naguilian" },
    { value: "palanan", label: "Palanan" },
    { value: "quezon", label: "Quezon" },
    { value: "quirino", label: "Quirino" },
    { value: "ramon", label: "Ramon" },
    { value: "reina_mercedes", label: "Reina Mercedes" },
    { value: "roxas", label: "Roxas" },
    { value: "san_agustin", label: "San Agustin" },
    { value: "san_guillermo", label: "San Guillermo" },
    { value: "san_isidro", label: "San Isidro" },
    { value: "san_manuel", label: "San Manuel" },
    { value: "san_mariano", label: "San Mariano" },
    { value: "san_mateo", label: "San Mateo" },
    { value: "san_pablo", label: "San Pablo" },
    { value: "santa_maria", label: "Santa Maria" },
    { value: "santiago", label: "Santiago" },
    { value: "santo_tomas", label: "Santo Tomas" },
    { value: "tumauini", label: "Tumauini" },
  ],

  kalinga: [
    { value: "balbalan", label: "Balbalan" },
    { value: "lubuagan", label: "Lubuagan" },
    { value: "pasil", label: "Pasil" },
    { value: "pinukpuk", label: "Pinukpuk" },
    { value: "rizal", label: "Rizal" },
    { value: "tabuk", label: "Tabuk" },
    { value: "tanudan", label: "Tanudan" },
    { value: "tinglayan", label: "Tinglayan" },
  ],

  la_union: [
    { value: "agoo", label: "Agoo" },
    { value: "aringay", label: "Aringay" },
    { value: "bacnotan", label: "Bacnotan" },
    { value: "bagulin", label: "Bagulin" },
    { value: "balaoan", label: "Balaoan" },
    { value: "bangar", label: "Bangar" },
    { value: "bauang", label: "Bauang" },
    { value: "burgos", label: "Burgos" },
    { value: "caba", label: "Caba" },
    { value: "luna_la_union", label: "Luna" },
    { value: "naguilian_la_union", label: "Naguilian" },
    { value: "pugo", label: "Pugo" },
    { value: "rosario_la_union", label: "Rosario" },
    { value: "san_fernando", label: "San Fernando" },
    { value: "san_gabriel", label: "San Gabriel" },
    { value: "san_juan_la_union", label: "San Juan" },
    { value: "santo_tomas_la_union", label: "Santo Tomas" },
    { value: "santol", label: "Santol" },
    { value: "sudipen", label: "Sudipen" },
    { value: "tubao", label: "Tubao" },
  ],

  laguna: [
    { value: "alaminos", label: "Alaminos" },
    { value: "bay", label: "Bay" },
    { value: "binan", label: "Biñan" },
    { value: "cabuyao", label: "Cabuyao" },
    { value: "calamba", label: "Calamba" },
    { value: "calauan", label: "Calauan" },
    { value: "cavinti", label: "Cavinti" },
    { value: "famy", label: "Famy" },
    { value: "kalayaan", label: "Kalayaan" },
    { value: "liliw", label: "Liliw" },
    { value: "los_banos", label: "Los Baños" },
    { value: "luisiana", label: "Luisiana" },
    { value: "lumban", label: "Lumban" },
    { value: "mabitac", label: "Mabitac" },
    { value: "magdalena", label: "Magdalena" },
    { value: "majayjay", label: "Majayjay" },
    { value: "nagcarlan", label: "Nagcarlan" },
    { value: "paete", label: "Paete" },
    { value: "pagsanjan", label: "Pagsanjan" },
    { value: "pakil", label: "Pakil" },
    { value: "pangil", label: "Pangil" },
    { value: "pila", label: "Pila" },
    { value: "rizal_laguna", label: "Rizal" },
    { value: "san_pablo", label: "San Pablo" },
    { value: "san_pedro", label: "San Pedro" },
    { value: "santa_cruz", label: "Santa Cruz" },
    { value: "santa_maria_laguna", label: "Santa Maria" },
    { value: "santa_rosa", label: "Santa Rosa" },
    { value: "siniloan", label: "Siniloan" },
    { value: "victoria", label: "Victoria" },
  ],
  lanao_del_norte: [
    { value: "bacolod", label: "Bacolod" },
    { value: "balo_i", label: "Balo-i" },
    { value: "baroy", label: "Baroy" },
    { value: "iligan", label: "Iligan" },
    { value: "kapatagan", label: "Kapatagan" },
    { value: "kauswagan", label: "Kauswagan" },
    { value: "kolambugan", label: "Kolambugan" },
    { value: "lala", label: "Lala" },
    { value: "linamon", label: "Linamon" },
    { value: "magsaysay", label: "Magsaysay" },
    { value: "maigo", label: "Maigo" },
    { value: "matungao", label: "Matungao" },
    { value: "munai", label: "Munai" },
    { value: "nunungan", label: "Nunungan" },
    { value: "pantao_ragat", label: "Pantao Ragat" },
    { value: "pantar", label: "Pantar" },
    { value: "poona_piagapo", label: "Poona Piagapo" },
    { value: "salvador", label: "Salvador" },
    { value: "sapad", label: "Sapad" },
    { value: "sultan_naga_dimaporo", label: "Sultan Naga Dimaporo" },
    { value: "tagoloan", label: "Tagoloan" },
    { value: "tangcal", label: "Tangcal" },
    { value: "tubod", label: "Tubod" },
  ],

  lanao_del_sur: [
    { value: "amai_manabilang", label: "Amai Manabilang" },
    { value: "bacolod_kalawi", label: "Bacolod-Kalawi" },
    { value: "balabagan", label: "Balabagan" },
    { value: "balindong", label: "Balindong" },
    { value: "bayang", label: "Bayang" },
    { value: "binidayan", label: "Binidayan" },
    { value: "buadiposo_buntong", label: "Buadiposo-Buntong" },
    { value: "bubong", label: "Bubong" },
    { value: "butig", label: "Butig" },
    { value: "calanogas", label: "Calanogas" },
    { value: "ditsaan_ramain", label: "Ditsaan-Ramain" },
    { value: "ganassi", label: "Ganassi" },
    { value: "kapai", label: "Kapai" },
    { value: "kapatagan", label: "Kapatagan" },
    { value: "lumba_bayabao", label: "Lumba-Bayabao" },
    { value: "lumbaca_unayan", label: "Lumbaca-Unayan" },
    { value: "lumbatan", label: "Lumbatan" },
    { value: "lumbayanague", label: "Lumbayanague" },
    { value: "madalum", label: "Madalum" },
    { value: "madamba", label: "Madamba" },
    { value: "maguing", label: "Maguing" },
    { value: "malabang", label: "Malabang" },
    { value: "marantao", label: "Marantao" },
    { value: "marawi", label: "Marawi" },
    { value: "marogong", label: "Marogong" },
    { value: "masiu", label: "Masiu" },
    { value: "mulondo", label: "Mulondo" },
    { value: "pagayawan", label: "Pagayawan" },
    { value: "piagapo", label: "Piagapo" },
    { value: "picong", label: "Picong" },
    { value: "poona_bayabao", label: "Poona Bayabao" },
    { value: "pualas", label: "Pualas" },
    { value: "saguiaran", label: "Saguiaran" },
    { value: "sultan_dumalondong", label: "Sultan Dumalondong" },
    { value: "tagoloan_ii", label: "Tagoloan II" },
    { value: "tamparan", label: "Tamparan" },
    { value: "taraka", label: "Taraka" },
    { value: "tubaran", label: "Tubaran" },
    { value: "tugaya", label: "Tugaya" },
    { value: "wao", label: "Wao" },
  ],

  leyte: [
    { value: "abuyog", label: "Abuyog" },
    { value: "alangalang", label: "Alangalang" },
    { value: "albuera", label: "Albuera" },
    { value: "babatngon", label: "Babatngon" },
    { value: "barugo", label: "Barugo" },
    { value: "bato", label: "Bato" },
    { value: "baybay", label: "Baybay" },
    { value: "burauen", label: "Burauen" },
    { value: "calubian", label: "Calubian" },
    { value: "capoocan", label: "Capoocan" },
    { value: "carigara", label: "Carigara" },
    { value: "dagami", label: "Dagami" },
    { value: "dulag", label: "Dulag" },
    { value: "hilongos", label: "Hilongos" },
    { value: "hindang", label: "Hindang" },
    { value: "inopacan", label: "Inopacan" },
    { value: "isabel", label: "Isabel" },
    { value: "jaro", label: "Jaro" },
    { value: "javier", label: "Javier" },
    { value: "julita", label: "Julita" },
    { value: "kananga", label: "Kananga" },
    { value: "la_paz", label: "La Paz" },
    { value: "leyte", label: "Leyte" },
    { value: "macarthur", label: "MacArthur" },
    { value: "mahaplag", label: "Mahaplag" },
    { value: "matag_ob", label: "Matag-ob" },
    { value: "mayorga", label: "Mayorga" },
    { value: "merida", label: "Merida" },
    { value: "ormoc", label: "Ormoc" },
    { value: "palo", label: "Palo" },
    { value: "palompon", label: "Palompon" },
    { value: "pastrana", label: "Pastrana" },
    { value: "san_isidro", label: "San Isidro" },
    { value: "san_miguel", label: "San Miguel" },
    { value: "santa_fe", label: "Santa Fe" },
    { value: "tabango", label: "Tabango" },
    { value: "tabontabon", label: "Tabontabon" },
    { value: "tacloban", label: "Tacloban" },
    { value: "tanauan", label: "Tanauan" },
    { value: "tolosa", label: "Tolosa" },
    { value: "tunga", label: "Tunga" },
    { value: "villaba", label: "Villaba" },
  ],
  maguindanao_del_norte: [
    { value: "barira", label: "Barira" },
    { value: "buldon", label: "Buldon" },
    { value: "cotabato_city", label: "Cotabato City" },
    { value: "datu_blah_t_sinsuat", label: "Datu Blah T. Sinsuat" },
    { value: "datu_odin_sinsuat", label: "Datu Odin Sinsuat" },
    { value: "kabuntalan", label: "Kabuntalan" },
    { value: "matanog", label: "Matanog" },
    { value: "northern_kabuntalan", label: "Northern Kabuntalan" },
    { value: "parang", label: "Parang" },
    { value: "sultan_kudarat", label: "Sultan Kudarat" },
    { value: "sultan_mastura", label: "Sultan Mastura" },
    { value: "talitay", label: "Talitay" },
    { value: "upi", label: "Upi" },
  ],

  maguindanao_del_sur: [
    { value: "ampatuan", label: "Ampatuan" },
    { value: "buluan", label: "Buluan" },
    { value: "datu_abdullah_sangki", label: "Datu Abdullah Sangki" },
    { value: "datu_anggal_midtimbang", label: "Datu Anggal Midtimbang" },
    { value: "datu_hoffer_ampatuan", label: "Datu Hoffer Ampatuan" },
    { value: "datu_montawal", label: "Datu Montawal" },
    { value: "datu_paglas", label: "Datu Paglas" },
    { value: "datu_piang", label: "Datu Piang" },
    { value: "datu_salibo", label: "Datu Salibo" },
    { value: "datu_saudi_ampatuan", label: "Datu Saudi-Ampatuan" },
    { value: "datu_unsay", label: "Datu Unsay" },
    { value: "general_salipada_k_pendatun", label: "General Salipada K. Pendatun" },
    { value: "guindulungan", label: "Guindulungan" },
    { value: "mamasapano", label: "Mamasapano" },
    { value: "mangudadatu", label: "Mangudadatu" },
    { value: "pagalungan", label: "Pagalungan" },
    { value: "paglat", label: "Paglat" },
    { value: "pandag", label: "Pandag" },
    { value: "rajah_buayan", label: "Rajah Buayan" },
    { value: "shariff_aguak", label: "Shariff Aguak" },
    { value: "shariff_saydona_mustapha", label: "Shariff Saydona Mustapha" },
    { value: "south_upi", label: "South Upi" },
    { value: "sultan_sa_barongis", label: "Sultan sa Barongis" },
    { value: "talayan", label: "Talayan" },
  ],
  marinduque: [
    { value: "boac", label: "Boac" },
    { value: "buenavista", label: "Buenavista" },
    { value: "gasan", label: "Gasan" },
    { value: "mogpog", label: "Mogpog" },
    { value: "santa_cruz", label: "Santa Cruz" },
    { value: "torrijos", label: "Torrijos" },
  ],

  masbate: [
    { value: "aroroy", label: "Aroroy" },
    { value: "baleno", label: "Baleno" },
    { value: "balud", label: "Balud" },
    { value: "batuan", label: "Batuan" },
    { value: "cataingan", label: "Cataingan" },
    { value: "cawayan", label: "Cawayan" },
    { value: "claveria", label: "Claveria" },
    { value: "dimasalang", label: "Dimasalang" },
    { value: "esperanza", label: "Esperanza" },
    { value: "mandaon", label: "Mandaon" },
    { value: "masbate_city", label: "Masbate City" },
    { value: "milagros", label: "Milagros" },
    { value: "mobo", label: "Mobo" },
    { value: "monreal", label: "Monreal" },
    { value: "palanas", label: "Palanas" },
    { value: "pio_v_corpus", label: "Pio V. Corpus" },
    { value: "placer", label: "Placer" },
    { value: "san_fernando", label: "San Fernando" },
    { value: "san_jacinto", label: "San Jacinto" },
    { value: "san_pascual", label: "San Pascual" },
    { value: "uson", label: "Uson" },
  ],

  metro_manila: [
    { value: "caloocan", label: "Caloocan" },
    { value: "las_pinas", label: "Las Piñas" },
    { value: "makati", label: "Makati" },
    { value: "malabon", label: "Malabon" },
    { value: "mandaluyong", label: "Mandaluyong" },
    { value: "manila", label: "Manila" },
    { value: "marikina", label: "Marikina" },
    { value: "muntinlupa", label: "Muntinlupa" },
    { value: "navotas", label: "Navotas" },
    { value: "paranaque", label: "Parañaque" },
    { value: "pasay", label: "Pasay" },
    { value: "pasig", label: "Pasig" },
    { value: "pateros", label: "Pateros" },
    { value: "quezon_city", label: "Quezon City" },
    { value: "san_juan", label: "San Juan" },
    { value: "taguig", label: "Taguig" },
    { value: "valenzuela", label: "Valenzuela" },
  ],
  misamis_oriental: [
    { value: "alubijid", label: "Alubijid" },
    { value: "balingasag", label: "Balingasag" },
    { value: "balingoan", label: "Balingoan" },
    { value: "binuangan", label: "Binuangan" },
    { value: "cagayan_de_oro", label: "Cagayan de Oro" },
    { value: "claveria", label: "Claveria" },
    { value: "el_salvador", label: "El Salvador" },
    { value: "gingoog", label: "Gingoog" },
    { value: "gitagum", label: "Gitagum" },
    { value: "initao", label: "Initao" },
    { value: "jasaan", label: "Jasaan" },
    { value: "kinoguitan", label: "Kinoguitan" },
    { value: "lagonglong", label: "Lagonglong" },
    { value: "laguindingan", label: "Laguindingan" },
    { value: "libertad", label: "Libertad" },
    { value: "lugait", label: "Lugait" },
    { value: "magsaysay", label: "Magsaysay" },
    { value: "manticao", label: "Manticao" },
    { value: "medina", label: "Medina" },
    { value: "naawan", label: "Naawan" },
    { value: "opol", label: "Opol" },
    { value: "salay", label: "Salay" },
    { value: "sugbongcogon", label: "Sugbongcogon" },
    { value: "tagoloan", label: "Tagoloan" },
    { value: "talisayan", label: "Talisayan" },
    { value: "villanueva", label: "Villanueva" },
  ],

  misamis_occidental: [
    { value: "aloran", label: "Aloran" },
    { value: "baliangao", label: "Baliangao" },
    { value: "bonifacio", label: "Bonifacio" },
    { value: "calamba", label: "Calamba" },
    { value: "clarin", label: "Clarin" },
    { value: "concepcion", label: "Concepcion" },
    { value: "don_victoriano_chiongbian", label: "Don Victoriano Chiongbian" },
    { value: "jimenez", label: "Jimenez" },
    { value: "lopez_jaena", label: "Lopez Jaena" },
    { value: "oroquieta", label: "Oroquieta" },
    { value: "ozamiz", label: "Ozamiz" },
    { value: "panaon", label: "Panaon" },
    { value: "plaridel", label: "Plaridel" },
    { value: "sapang_dalaga", label: "Sapang Dalaga" },
    { value: "sinacaban", label: "Sinacaban" },
    { value: "tangub", label: "Tangub" },
    { value: "tudela", label: "Tudela" },
  ],
  mountain_province: [
    { value: "barlig", label: "Barlig" },
    { value: "bauko", label: "Bauko" },
    { value: "besao", label: "Besao" },
    { value: "bontoc", label: "Bontoc" },
    { value: "natonin", label: "Natonin" },
    { value: "paracelis", label: "Paracelis" },
    { value: "sabangan", label: "Sabangan" },
    { value: "sadanga", label: "Sadanga" },
    { value: "sagada", label: "Sagada" },
    { value: "tadian", label: "Tadian" },
  ],

  negros_occidental: [
    { value: "bacolod", label: "Bacolod" },
    { value: "bago", label: "Bago" },
    { value: "binalbagan", label: "Binalbagan" },
    { value: "cadiz", label: "Cadiz" },
    { value: "calatrava", label: "Calatrava" },
    { value: "candoni", label: "Candoni" },
    { value: "cauayan", label: "Cauayan" },
    { value: "don_salvador_benedicto", label: "Don Salvador Benedicto" },
    { value: "enrique_b_magalona", label: "Enrique B. Magalona" },
    { value: "escalante", label: "Escalante" },
    { value: "himamaylan", label: "Himamaylan" },
    { value: "hinigaran", label: "Hinigaran" },
    { value: "hinoba_an", label: "Hinoba-an" },
    { value: "ilog", label: "Ilog" },
    { value: "isabela", label: "Isabela" },
    { value: "kabankalan", label: "Kabankalan" },
    { value: "la_carlota", label: "La Carlota" },
    { value: "la_castellana", label: "La Castellana" },
    { value: "manapla", label: "Manapla" },
    { value: "moises_padilla", label: "Moises Padilla" },
    { value: "murcia", label: "Murcia" },
    { value: "pontevedra", label: "Pontevedra" },
    { value: "pulupandan", label: "Pulupandan" },
    { value: "sagay", label: "Sagay" },
    { value: "san_carlos", label: "San Carlos" },
    { value: "san_enrique", label: "San Enrique" },
    { value: "silay", label: "Silay" },
    { value: "sipalay", label: "Sipalay" },
    { value: "talisay", label: "Talisay" },
    { value: "toboso", label: "Toboso" },
    { value: "valladolid", label: "Valladolid" },
    { value: "victorias", label: "Victorias" },
  ],

  negros_oriental: [
    { value: "amlan", label: "Amlan" },
    { value: "ayungon", label: "Ayungon" },
    { value: "bacong", label: "Bacong" },
    { value: "bais", label: "Bais" },
    { value: "basay", label: "Basay" },
    { value: "bayawan", label: "Bayawan" },
    { value: "bindoy", label: "Bindoy" },
    { value: "canlaon", label: "Canlaon" },
    { value: "dauin", label: "Dauin" },
    { value: "dumaguete", label: "Dumaguete" },
    { value: "guihulngan", label: "Guihulngan" },
    { value: "jimalalud", label: "Jimalalud" },
    { value: "la_libertad", label: "La Libertad" },
    { value: "mabinay", label: "Mabinay" },
    { value: "manjuyod", label: "Manjuyod" },
    { value: "pamplona", label: "Pamplona" },
    { value: "san_jose", label: "San Jose" },
    { value: "santa_catalina", label: "Santa Catalina" },
    { value: "siaton", label: "Siaton" },
    { value: "sibulan", label: "Sibulan" },
    { value: "tanjay", label: "Tanjay" },
    { value: "tayasan", label: "Tayasan" },
    { value: "valencia", label: "Valencia" },
    { value: "vallehermoso", label: "Vallehermoso" },
    { value: "zamboanguita", label: "Zamboanguita" },
  ],
  northern_samar: [
    { value: "allen", label: "Allen" },
    { value: "biri", label: "Biri" },
    { value: "bobon", label: "Bobon" },
    { value: "capul", label: "Capul" },
    { value: "catarman", label: "Catarman" },
    { value: "catubig", label: "Catubig" },
    { value: "gamay", label: "Gamay" },
    { value: "laoang", label: "Laoang" },
    { value: "lapinig", label: "Lapinig" },
    { value: "las_navas", label: "Las Navas" },
    { value: "lavezares", label: "Lavezares" },
    { value: "lope_de_vega", label: "Lope de Vega" },
    { value: "mapanas", label: "Mapanas" },
    { value: "mondragon", label: "Mondragon" },
    { value: "palapag", label: "Palapag" },
    { value: "pambujan", label: "Pambujan" },
    { value: "rosario", label: "Rosario" },
    { value: "san_antonio", label: "San Antonio" },
    { value: "san_isidro", label: "San Isidro" },
    { value: "san_jose", label: "San Jose" },
    { value: "san_roque", label: "San Roque" },
    { value: "san_vicente", label: "San Vicente" },
    { value: "silvino_lobos", label: "Silvino Lobos" },
    { value: "victoria", label: "Victoria" },
  ],

  nueva_ecija: [
    { value: "aliaga", label: "Aliaga" },
    { value: "bongabon", label: "Bongabon" },
    { value: "cabanatuan", label: "Cabanatuan" },
    { value: "cabiao", label: "Cabiao" },
    { value: "carranglan", label: "Carranglan" },
    { value: "cuyapo", label: "Cuyapo" },
    { value: "gabaldon", label: "Gabaldon" },
    { value: "gapan", label: "Gapan" },
    { value: "general_mamerto_natividad", label: "General Mamerto Natividad" },
    { value: "general_tinio", label: "General Tinio" },
    { value: "guimba", label: "Guimba" },
    { value: "jaen", label: "Jaen" },
    { value: "laur", label: "Laur" },
    { value: "licab", label: "Licab" },
    { value: "llanera", label: "Llanera" },
    { value: "lupao", label: "Lupao" },
    { value: "munoz", label: "Muñoz" },
    { value: "nampicuan", label: "Nampicuan" },
    { value: "palayan", label: "Palayan" },
    { value: "pantabangan", label: "Pantabangan" },
    { value: "penaranda", label: "Peñaranda" },
    { value: "quezon", label: "Quezon" },
    { value: "rizal", label: "Rizal" },
    { value: "san_antonio", label: "San Antonio" },
    { value: "san_isidro", label: "San Isidro" },
    { value: "san_jose", label: "San Jose" },
    { value: "san_leonardo", label: "San Leonardo" },
    { value: "santa_rosa", label: "Santa Rosa" },
    { value: "santo_domingo", label: "Santo Domingo" },
    { value: "talavera", label: "Talavera" },
    { value: "talugtug", label: "Talugtug" },
    { value: "zaragoza", label: "Zaragoza" },
  ],

  nueva_vizcaya: [
    { value: "alfonso_castaneda", label: "Alfonso Castañeda" },
    { value: "ambaguio", label: "Ambaguio" },
    { value: "aritao", label: "Aritao" },
    { value: "bagabag", label: "Bagabag" },
    { value: "bambang", label: "Bambang" },
    { value: "bayombong", label: "Bayombong" },
    { value: "diadi", label: "Diadi" },
    { value: "dupax_del_norte", label: "Dupax del Norte" },
    { value: "dupax_del_sur", label: "Dupax del Sur" },
    { value: "kasibu", label: "Kasibu" },
    { value: "kayapa", label: "Kayapa" },
    { value: "quezon", label: "Quezon" },
    { value: "santa_fe", label: "Santa Fe" },
    { value: "solano", label: "Solano" },
    { value: "villaverde", label: "Villaverde" },
  ],
  occidental_mindoro: [
    { value: "abra_de_ilog", label: "Abra de Ilog" },
    { value: "calintaan", label: "Calintaan" },
    { value: "looc", label: "Looc" },
    { value: "lubang", label: "Lubang" },
    { value: "magsaysay", label: "Magsaysay" },
    { value: "mamburao", label: "Mamburao" },
    { value: "paluan", label: "Paluan" },
    { value: "rizal", label: "Rizal" },
    { value: "sablayan", label: "Sablayan" },
    { value: "san_jose", label: "San Jose" },
    { value: "santa_cruz", label: "Santa Cruz" },
  ],

  oriental_mindoro: [
    { value: "baco", label: "Baco" },
    { value: "bansud", label: "Bansud" },
    { value: "bongabong", label: "Bongabong" },
    { value: "bulalacao", label: "Bulalacao" },
    { value: "calapan", label: "Calapan" },
    { value: "gloria", label: "Gloria" },
    { value: "mansalay", label: "Mansalay" },
    { value: "naujan", label: "Naujan" },
    { value: "pinamalayan", label: "Pinamalayan" },
    { value: "pola", label: "Pola" },
    { value: "puerto_galera", label: "Puerto Galera" },
    { value: "roxas", label: "Roxas" },
    { value: "san_teodoro", label: "San Teodoro" },
    { value: "socorro", label: "Socorro" },
    { value: "victoria", label: "Victoria" },
  ],

  palawan: [
    { value: "aborlan", label: "Aborlan" },
    { value: "agutaya", label: "Agutaya" },
    { value: "araceli", label: "Araceli" },
    { value: "balabac", label: "Balabac" },
    { value: "bataraza", label: "Bataraza" },
    { value: "brookes_point", label: "Brooke's Point" },
    { value: "busuanga", label: "Busuanga" },
    { value: "cagayancillo", label: "Cagayancillo" },
    { value: "coron", label: "Coron" },
    { value: "culion", label: "Culion" },
    { value: "cuyo", label: "Cuyo" },
    { value: "dumaran", label: "Dumaran" },
    { value: "el_nido", label: "El Nido" },
    { value: "kalayaan", label: "Kalayaan" },
    { value: "linapacan", label: "Linapacan" },
    { value: "magsaysay_palawan", label: "Magsaysay" },
    { value: "narra", label: "Narra" },
    { value: "puerto_princesa", label: "Puerto Princesa" },
    { value: "quezon_palawan", label: "Quezon" },
    { value: "rizal_palawan", label: "Rizal" },
    { value: "roxas_palawan", label: "Roxas" },
    { value: "san_vicente", label: "San Vicente" },
    { value: "sofronio_espanola", label: "Sofronio Española" },
    { value: "taytay_palawan", label: "Taytay" },
  ],
  pampanga: [
    { value: "angeles", label: "Angeles" },
    { value: "apalit", label: "Apalit" },
    { value: "arayat", label: "Arayat" },
    { value: "bacolor", label: "Bacolor" },
    { value: "candaba", label: "Candaba" },
    { value: "floridablanca", label: "Floridablanca" },
    { value: "guagua", label: "Guagua" },
    { value: "lubao", label: "Lubao" },
    { value: "mabalacat", label: "Mabalacat" },
    { value: "macabebe", label: "Macabebe" },
    { value: "magalang", label: "Magalang" },
    { value: "masantol", label: "Masantol" },
    { value: "mexico", label: "Mexico" },
    { value: "minalin", label: "Minalin" },
    { value: "porac", label: "Porac" },
    { value: "san_fernando", label: "San Fernando" },
    { value: "san_luis", label: "San Luis" },
    { value: "san_simon", label: "San Simon" },
    { value: "santa_ana", label: "Santa Ana" },
    { value: "santa_rita", label: "Santa Rita" },
    { value: "santo_tomas", label: "Santo Tomas" },
    { value: "sasmuan", label: "Sasmuan" },
  ],
  pangasinan: [
    { value: "agno", label: "Agno" },
    { value: "aguilar", label: "Aguilar" },
    { value: "alaminos", label: "Alaminos" },
    { value: "alcala", label: "Alcala" },
    { value: "anda", label: "Anda" },
    { value: "asingan", label: "Asingan" },
    { value: "balungao", label: "Balungao" },
    { value: "bani", label: "Bani" },
    { value: "basista", label: "Basista" },
    { value: "bautista", label: "Bautista" },
    { value: "bayambang", label: "Bayambang" },
    { value: "binalonan", label: "Binalonan" },
    { value: "binmaley", label: "Binmaley" },
    { value: "bolinao", label: "Bolinao" },
    { value: "bugallon", label: "Bugallon" },
    { value: "burgos", label: "Burgos" },
    { value: "calasiao", label: "Calasiao" },
    { value: "dagupan", label: "Dagupan" },
    { value: "dasol", label: "Dasol" },
    { value: "infanta", label: "Infanta" },
    { value: "labrador", label: "Labrador" },
    { value: "laoac", label: "Laoac" },
    { value: "lingayen", label: "Lingayen" },
    { value: "mabini", label: "Mabini" },
    { value: "malasiqui", label: "Malasiqui" },
    { value: "manaoag", label: "Manaoag" },
    { value: "mangaldan", label: "Mangaldan" },
    { value: "mangatarem", label: "Mangatarem" },
    { value: "mapandan", label: "Mapandan" },
    { value: "natividad", label: "Natividad" },
    { value: "pozorrubio", label: "Pozorrubio" },
    { value: "rosales", label: "Rosales" },
    { value: "san_carlos", label: "San Carlos" },
    { value: "san_fabian", label: "San Fabian" },
    { value: "san_jacinto", label: "San Jacinto" },
    { value: "san_manuel", label: "San Manuel" },
    { value: "san_nicolas", label: "San Nicolas" },
    { value: "san_quintin", label: "San Quintin" },
    { value: "santa_barbara", label: "Santa Barbara" },
    { value: "santa_maria", label: "Santa Maria" },
    { value: "santo_tomas", label: "Santo Tomas" },
    { value: "sison", label: "Sison" },
    { value: "sual", label: "Sual" },
    { value: "tayug", label: "Tayug" },
    { value: "umingan", label: "Umingan" },
    { value: "urbiztondo", label: "Urbiztondo" },
    { value: "urdaneta", label: "Urdaneta" },
    { value: "villasis", label: "Villasis" },
  ],
  quezon: [
    { value: "agdangan", label: "Agdangan" },
    { value: "alabat", label: "Alabat" },
    { value: "atimonan", label: "Atimonan" },
    { value: "buenavista", label: "Buenavista" },
    { value: "burdeos", label: "Burdeos" },
    { value: "calauag", label: "Calauag" },
    { value: "candelaria", label: "Candelaria" },
    { value: "catanauan", label: "Catanauan" },
    { value: "dolores", label: "Dolores" },
    { value: "general_luna", label: "General Luna" },
    { value: "general_nakar", label: "General Nakar" },
    { value: "guinayangan", label: "Guinayangan" },
    { value: "gumaca", label: "Gumaca" },
    { value: "infanta", label: "Infanta" },
    { value: "jomalig", label: "Jomalig" },
    { value: "lopez", label: "Lopez" },
    { value: "lucban", label: "Lucban" },
    { value: "lucena", label: "Lucena" },
    { value: "macalelon", label: "Macalelon" },
    { value: "mauban", label: "Mauban" },
    { value: "mulanay", label: "Mulanay" },
    { value: "padre_burgos", label: "Padre Burgos" },
    { value: "pagbilao", label: "Pagbilao" },
    { value: "panukulan", label: "Panukulan" },
    { value: "patnanungan", label: "Patnanungan" },
    { value: "perez", label: "Perez" },
    { value: "pitogo", label: "Pitogo" },
    { value: "plaridel", label: "Plaridel" },
    { value: "polillo", label: "Polillo" },
    { value: "quezon", label: "Quezon" },
    { value: "real", label: "Real" },
    { value: "sampaloc", label: "Sampaloc" },
    { value: "san_andres", label: "San Andres" },
    { value: "san_antonio", label: "San Antonio" },
    { value: "san_francisco", label: "San Francisco" },
    { value: "san_narciso", label: "San Narciso" },
    { value: "sariaya", label: "Sariaya" },
    { value: "tagkawayan", label: "Tagkawayan" },
    { value: "tayabas", label: "Tayabas" },
    { value: "tiaong", label: "Tiaong" },
    { value: "unisan", label: "Unisan" },
  ],

  quirino: [
    { value: "aglipay", label: "Aglipay" },
    { value: "cabarroguis", label: "Cabarroguis" },
    { value: "diffun", label: "Diffun" },
    { value: "maddela", label: "Maddela" },
    { value: "nagtipunan", label: "Nagtipunan" },
    { value: "saguday", label: "Saguday" },
  ],

  rizal: [
    { value: "angono", label: "Angono" },
    { value: "antipolo", label: "Antipolo" },
    { value: "baras", label: "Baras" },
    { value: "binangonan", label: "Binangonan" },
    { value: "cainta", label: "Cainta" },
    { value: "cardona", label: "Cardona" },
    { value: "jalajala", label: "Jalajala" },
    { value: "morong", label: "Morong" },
    { value: "pililla", label: "Pililla" },
    { value: "rodriguez", label: "Rodriguez" },
    { value: "san_mateo", label: "San Mateo" },
    { value: "tanay", label: "Tanay" },
    { value: "taytay", label: "Taytay" },
    { value: "teresa", label: "Teresa" },
  ],

  romblon: [
    { value: "alcantara", label: "Alcantara" },
    { value: "banton", label: "Banton" },
    { value: "cajidiocan", label: "Cajidiocan" },
    { value: "calatrava", label: "Calatrava" },
    { value: "concepcion", label: "Concepcion" },
    { value: "corcuera", label: "Corcuera" },
    { value: "ferrol", label: "Ferrol" },
    { value: "looc", label: "Looc" },
    { value: "magdiwang", label: "Magdiwang" },
    { value: "odiongan", label: "Odiongan" },
    { value: "romblon", label: "Romblon" },
    { value: "san_agustin", label: "San Agustin" },
    { value: "san_andres", label: "San Andres" },
    { value: "san_fernando", label: "San Fernando" },
    { value: "san_jose", label: "San Jose" },
    { value: "santa_fe", label: "Santa Fe" },
    { value: "santa_maria", label: "Santa Maria" },
  ],

  samar: [
    { value: "almagro", label: "Almagro" },
    { value: "basey", label: "Basey" },
    { value: "calbayog", label: "Calbayog" },
    { value: "calbiga", label: "Calbiga" },
    { value: "catbalogan", label: "Catbalogan" },
    { value: "daram", label: "Daram" },
    { value: "gandara", label: "Gandara" },
    { value: "hinabangan", label: "Hinabangan" },
    { value: "jiabong", label: "Jiabong" },
    { value: "marabut", label: "Marabut" },
    { value: "matuguinao", label: "Matuguinao" },
    { value: "motiong", label: "Motiong" },
    { value: "pagsanghan", label: "Pagsanghan" },
    { value: "paranas", label: "Paranas" },
    { value: "pinabacdao", label: "Pinabacdao" },
    { value: "san_jorge", label: "San Jorge" },
    { value: "san_jose_de_buan", label: "San Jose de Buan" },
    { value: "san_sebastian", label: "San Sebastian" },
    { value: "santa_margarita", label: "Santa Margarita" },
    { value: "santa_rita", label: "Santa Rita" },
    { value: "santo_nino", label: "Santo Nino" },
    { value: "tagapul-an", label: "Tagapul-an" },
    { value: "talalora", label: "Talalora" },
    { value: "tarangnan", label: "Tarangnan" },
    { value: "villareal", label: "Villareal" },
    { value: "zumarraga", label: "Zumarraga" },
  ],
  sarangani: [
    { value: "alabel", label: "Alabel" },
    { value: "glan", label: "Glan" },
    { value: "kiamba", label: "Kiamba" },
    { value: "maasim", label: "Maasim" },
    { value: "maitum", label: "Maitum" },
    { value: "malapatan", label: "Malapatan" },
    { value: "malungon", label: "Malungon" },
  ],
  sorsogon: [
    { value: "barcelona", label: "Barcelona" },
    { value: "bulan", label: "Bulan" },
    { value: "bulusan", label: "Bulusan" },
    { value: "casiguran", label: "Casiguran" },
    { value: "castilla", label: "Castilla" },
    { value: "donsol", label: "Donsol" },
    { value: "gubat", label: "Gubat" },
    { value: "irosin", label: "Irosin" },
    { value: "juban", label: "Juban" },
    { value: "magallanes", label: "Magallanes" },
    { value: "matnog", label: "Matnog" },
    { value: "pilar", label: "Pilar" },
    { value: "prieto_diaz", label: "Prieto Diaz" },
    { value: "santa_magdalena", label: "Santa Magdalena" },
    { value: "sorsogon_city", label: "Sorsogon City" },
  ],

  south_cotabato: [
    { value: "banga", label: "Banga" },
    { value: "general_santos", label: "General Santos" },
    { value: "koronadal", label: "Koronadal" },
    { value: "lake_sebu", label: "Lake Sebu" },
    { value: "norala", label: "Norala" },
    { value: "polomolok", label: "Polomolok" },
    { value: "santo_nino", label: "Santo Niño" },
    { value: "surallah", label: "Surallah" },
    { value: "t_boli", label: "T'Boli" },
    { value: "tampakan", label: "Tampakan" },
    { value: "tantangan", label: "Tantangan" },
    { value: "tupi", label: "Tupi" },
  ],
  southern_leyte: [
    { value: "anahawan", label: "Anahawan" },
    { value: "bontoc", label: "Bontoc" },
    { value: "hinunangan", label: "Hinunangan" },
    { value: "hinundayan", label: "Hinundayan" },
    { value: "libagon", label: "Libagon" },
    { value: "liloan", label: "Liloan" },
    { value: "limasawa", label: "Limasawa" },
    { value: "maasin", label: "Maasin" },
    { value: "macrohon", label: "Macrohon" },
    { value: "malitbog", label: "Malitbog" },
    { value: "padre_burgos", label: "Padre Burgos" },
    { value: "pintuyan", label: "Pintuyan" },
    { value: "saint_bernard", label: "Saint Bernard" },
    { value: "san_francisco", label: "San Francisco" },
    { value: "san_juan", label: "San Juan" },
    { value: "san_ricardo", label: "San Ricardo" },
    { value: "silago", label: "Silago" },
    { value: "sogod", label: "Sogod" },
    { value: "tomas_oppus", label: "Tomas Oppus" },
  ],

  sultan_kudarat: [
    { value: "bagumbayan", label: "Bagumbayan" },
    { value: "columbio", label: "Columbio" },
    { value: "esperanza", label: "Esperanza" },
    { value: "isulan", label: "Isulan" },
    { value: "kalamansig", label: "Kalamansig" },
    { value: "lambayong", label: "Lambayong" },
    { value: "lebak", label: "Lebak" },
    { value: "lutayan", label: "Lutayan" },
    { value: "palimbang", label: "Palimbang" },
    { value: "president_quirino", label: "President Quirino" },
    { value: "senator_ninoy_aquino", label: "Senator Ninoy Aquino" },
    { value: "tacurong", label: "Tacurong" },
  ],

  sulu: [
    { value: "banguingui", label: "Banguingui" },
    { value: "hadji_panglima_tahil", label: "Hadji Panglima Tahil" },
    { value: "indanan", label: "Indanan" },
    { value: "jolo", label: "Jolo" },
    { value: "kalingalan_caluang", label: "Kalingalan Caluang" },
    { value: "lugus", label: "Lugus" },
    { value: "luuk", label: "Luuk" },
    { value: "maimbung", label: "Maimbung" },
    { value: "omar", label: "Omar" },
    { value: "panamao", label: "Panamao" },
    { value: "pandami", label: "Pandami" },
    { value: "panglima_estino", label: "Panglima Estino" },
    { value: "pangutaran", label: "Pangutaran" },
    { value: "parang", label: "Parang" },
    { value: "pata", label: "Pata" },
    { value: "patikul", label: "Patikul" },
    { value: "siasi", label: "Siasi" },
    { value: "talipao", label: "Talipao" },
    { value: "tapul", label: "Tapul" },
  ],
  surigao_del_norte: [
    { value: "alegria", label: "Alegria" },
    { value: "bacuag", label: "Bacuag" },
    { value: "burgos", label: "Burgos" },
    { value: "claver", label: "Claver" },
    { value: "dapa", label: "Dapa" },
    { value: "del_carmen", label: "Del Carmen" },
    { value: "general_luna", label: "General Luna" },
    { value: "gigaquit", label: "Gigaquit" },
    { value: "mainit", label: "Mainit" },
    { value: "malimono", label: "Malimono" },
    { value: "pilar", label: "Pilar" },
    { value: "placer", label: "Placer" },
    { value: "san_benito", label: "San Benito" },
    { value: "san_francisco", label: "San Francisco" },
    { value: "san_isidro", label: "San Isidro" },
    { value: "santa_monica", label: "Santa Monica" },
    { value: "sison", label: "Sison" },
    { value: "socorro", label: "Socorro" },
    { value: "surigao_city", label: "Surigao City" },
    { value: "tagana_an", label: "Tagana-an" },
    { value: "tubod", label: "Tubod" },
  ],

  surigao_del_sur: [
    { value: "barobo", label: "Barobo" },
    { value: "bayabas", label: "Bayabas" },
    { value: "bislig", label: "Bislig" },
    { value: "cagwait", label: "Cagwait" },
    { value: "cantilan", label: "Cantilan" },
    { value: "carmen", label: "Carmen" },
    { value: "carrascal", label: "Carrascal" },
    { value: "cortes", label: "Cortes" },
    { value: "hinatuan", label: "Hinatuan" },
    { value: "lanuza", label: "Lanuza" },
    { value: "lianga", label: "Lianga" },
    { value: "lingig", label: "Lingig" },
    { value: "madrid", label: "Madrid" },
    { value: "marihatag", label: "Marihatag" },
    { value: "san_agustin", label: "San Agustin" },
    { value: "san_miguel", label: "San Miguel" },
    { value: "tagbina", label: "Tagbina" },
    { value: "tago", label: "Tago" },
    { value: "tandag", label: "Tandag" },
  ],

  tarlac: [
    { value: "anao", label: "Anao" },
    { value: "bamban", label: "Bamban" },
    { value: "camiling", label: "Camiling" },
    { value: "capas", label: "Capas" },
    { value: "concepcion", label: "Concepcion" },
    { value: "gerona", label: "Gerona" },
    { value: "la_paz", label: "La Paz" },
    { value: "mayantoc", label: "Mayantoc" },
    { value: "moncada", label: "Moncada" },
    { value: "paniqui", label: "Paniqui" },
    { value: "pura", label: "Pura" },
    { value: "ramos", label: "Ramos" },
    { value: "san_clemente", label: "San Clemente" },
    { value: "san_jose", label: "San Jose" },
    { value: "san_manuel", label: "San Manuel" },
    { value: "santa_ignacia", label: "Santa Ignacia" },
    { value: "tarlac_city", label: "Tarlac City" },
    { value: "victoria", label: "Victoria" },
  ],
  tawi_tawi: [
    { value: "bongao", label: "Bongao" },
    { value: "languyan", label: "Languyan" },
    { value: "mapun", label: "Mapun" },
    { value: "panglima_sugala", label: "Panglima Sugala" },
    { value: "sapa_sapa", label: "Sapa-Sapa" },
    { value: "sibutu", label: "Sibutu" },
    { value: "simunul", label: "Simunul" },
    { value: "sitangkai", label: "Sitangkai" },
    { value: "south_ubian", label: "South Ubian" },
    { value: "tandubas", label: "Tandubas" },
    { value: "turtle_islands", label: "Turtle Islands" },
  ],

  zambales: [
    { value: "botolan", label: "Botolan" },
    { value: "cabangan", label: "Cabangan" },
    { value: "candelaria", label: "Candelaria" },
    { value: "castillejos", label: "Castillejos" },
    { value: "iba", label: "Iba" },
    { value: "masinloc", label: "Masinloc" },
    { value: "olongapo", label: "Olongapo" },
    { value: "palauig", label: "Palauig" },
    { value: "san_antonio", label: "San Antonio" },
    { value: "san_felipe", label: "San Felipe" },
    { value: "san_marcelino", label: "San Marcelino" },
    { value: "san_narciso", label: "San Narciso" },
    { value: "santa_cruz", label: "Santa Cruz" },
    { value: "subic", label: "Subic" },
  ],

  zamboanga_del_norte: [
    { value: "baliguian", label: "Baliguian" },
    { value: "dapitan", label: "Dapitan" },
    { value: "dipolog", label: "Dipolog" },
    { value: "godod", label: "Godod" },
    { value: "gutalac", label: "Gutalac" },
    { value: "jose_dalman", label: "Jose Dalman" },
    { value: "kalawit", label: "Kalawit" },
    { value: "katipunan", label: "Katipunan" },
    { value: "la_libertad", label: "La Libertad" },
    { value: "labason", label: "Labason" },
    { value: "leon_b_postigo", label: "Leon B. Postigo" },
    { value: "liloy", label: "Liloy" },
    { value: "manukan", label: "Manukan" },
    { value: "mutia", label: "Mutia" },
    { value: "pinan", label: "Piñan" },
    { value: "polanco", label: "Polanco" },
    { value: "rizal", label: "Rizal" },
    { value: "roxas", label: "Roxas" },
    { value: "salug", label: "Salug" },
    { value: "sergio_osmena", label: "Sergio Osmeña" },
    { value: "siayan", label: "Siayan" },
    { value: "sibuco", label: "Sibuco" },
    { value: "sibutad", label: "Sibutad" },
    { value: "sindangan", label: "Sindangan" },
    { value: "siocon", label: "Siocon" },
    { value: "sirawai", label: "Sirawai" },
    { value: "tampilisan", label: "Tampilisan" },
  ],
  zamboanga_del_sur: [
    { value: "aurora", label: "Aurora" },
    { value: "bayog", label: "Bayog" },
    { value: "dimataling", label: "Dimataling" },
    { value: "dinas", label: "Dinas" },
    { value: "dumalinao", label: "Dumalinao" },
    { value: "dumingag", label: "Dumingag" },
    { value: "guipos", label: "Guipos" },
    { value: "josefina", label: "Josefina" },
    { value: "kumalarang", label: "Kumalarang" },
    { value: "labangan", label: "Labangan" },
    { value: "lakewood", label: "Lakewood" },
    { value: "lapuyan", label: "Lapuyan" },
    { value: "mahayag", label: "Mahayag" },
    { value: "margosatubig", label: "Margosatubig" },
    { value: "midsalip", label: "Midsalip" },
    { value: "molave", label: "Molave" },
    { value: "pagadian", label: "Pagadian" },
    { value: "pitogo", label: "Pitogo" },
    { value: "ramon_magsaysay", label: "Ramon Magsaysay" },
    { value: "san_miguel", label: "San Miguel" },
    { value: "san_pablo", label: "San Pablo" },
    { value: "sominot", label: "Sominot" },
    { value: "tabina", label: "Tabina" },
    { value: "tambulig", label: "Tambulig" },
    { value: "tigbao", label: "Tigbao" },
    { value: "tukuran", label: "Tukuran" },
    { value: "vincenzo_a_sagun", label: "Vincenzo A. Sagun" },
    { value: "zamboanga_city", label: "Zamboanga City" },
  ],

  zamboanga_sibugay: [
    { value: "alicia", label: "Alicia" },
    { value: "buug", label: "Buug" },
    { value: "diplahan", label: "Diplahan" },
    { value: "imelda", label: "Imelda" },
    { value: "ipil", label: "Ipil" },
    { value: "kabasalan", label: "Kabasalan" },
    { value: "mabuhay", label: "Mabuhay" },
    { value: "malangas", label: "Malangas" },
    { value: "naga", label: "Naga" },
    { value: "olutanga", label: "Olutanga" },
    { value: "payao", label: "Payao" },
    { value: "roseller_lim", label: "Roseller Lim" },
    { value: "siay", label: "Siay" },
    { value: "talusan", label: "Talusan" },
    { value: "titay", label: "Titay" },
    { value: "tungawan", label: "Tungawan" },
  ],
};
